day_list = {'PSH.L': 840, 'IMI.L': 840, 'CTEC.L': 720, 'ABDN': 840, 'UTG.L': 840, 'SMDS.L': 840, 'LMP.L': 840, 'INF.L': 840, 'IMB.L': 840, 'HWDN.L': 840, 'Hiscox Ltd': 840, 'HL.L': 840, 'GAW.L': 840, 'DPLM.L': 840, 'DCC.L': 840, 'BTRW.L': 840, 'AHT.L': 840, 'ALW.L': 840, 'AAF.L': 690, 'NWG.L': 690, 'ABF.L': 810, 'IBE.MC': 840, '3IN.L': 780, 'A': 840, 'AAL': 840, 'AAL.L': 780, 'AAPL': 840, 'ABBV': 840, 'ABT': 840, 'ACI': 840, 'ACN': 840, 'ADBE': 840, 'ADI': 840, 'ADM': 840, 'ADM.L': 840, 'ADSK': 840, 'AEE': 840, 'AEP': 840, 'AES': 840, 'AFL': 840, 'AIG': 840, 'AKAM': 840, 'ALGN': 840, 'ALK': 840, 'ALL': 840, 'ALLE': 840, 'AMAT': 840, 'AMCR': 840, 'AMD': 840, 'AME': 840, 'AMGN': 840, 'AMZN': 840, 'ANET': 840, 'ANSS': 840, 'ANTO.L': 840, 'AON': 840, 'AOS': 840, 'APA': 840, 'APD': 840, 'APTV': 840, 'ARE': 840, 'ARW': 840, 'ATO': 840, 'AUTO.L': 840, 'AV.L': 840, 'AVB': 840, 'AVGO': 840, 'AXP': 840, 'AZN.L': 840, 'AZO': 840, 'BA': 840, 'BA.L': 840, 'BAC': 840, 'BALL': 840, 'BARC.L': 780, 'BATS.L': 840, 'BAX': 840, 'BBWI': 840, 'BBY': 840, 'BDEV.L': 840, 'BDX': 840, 'BEN': 840, 'BIIB': 840, 'BIO': 840, 'BKG.L': 780, 'BKNG': 840, 'BKR': 840, 'BLK': 840, 'BLND.L': 840, 'BMY': 840, 'BNZL.L': 840, 'BP.L': 750, 'BR': 840, 'BRBY.L': 840, 'BRK-B': 840, 'BSX': 840, 'BT-A.L': 840, 'BWA': 840, 'BXP': 840, 'BYDDY': 840, 'C': 840, 'CAG': 840, 'CAT': 840, 'CB': 840, 'CBOE': 840, 'CBRE': 840, 'CCH.L': 840, 'CE': 840, 'CHD': 840, 'CHTR': 840, 'CI': 840, 'CINF': 840, 'CL': 840, 'CLX': 840, 'CMCSA': 840, 'CME': 840, 'CMG': 840, 'CMI': 840, 'CMS': 840, 'CNA.L': 840, 'CNC': 840, 'CNP': 840, 'COO': 840, 'COP': 840, 'COST': 840, 'CPG.L': 840, 'CPRT': 840, 'CRDA.L': 840, 'CRH.L': 840, 'CRM': 840, 'CSCO': 840, 'CSX': 840, 'CTAS': 840, 'CTRA': 840, 'CVS': 840, 'CVX': 840, 'D': 840, 'DAL': 840, 'DD': 840, 'DE': 840, 'DEO': 840, 'DFS': 840, 'DG': 840, 'DGE.L': 840, 'DHI': 840, 'DHR': 840, 'DIS': 840, 'DLR': 840, 'DLTR': 840, 'DOV': 840, 'DOW': 840, 'DRI': 840, 'DTE': 840, 'DUK': 840, 'DVA': 840, 'DVN': 840, 'EA': 840, 'EBAY': 840, 'ECL': 840, 'ED': 840, 'EFX': 840, 'EIX': 840, 'EL': 840, 'ELV': 840, 'EMN': 840, 'EMR': 840, 'ENPH': 840, 'EOG': 840, 'EPAM': 840, 'EQIX': 840, 'EQR': 840, 'EQT': 840, 'ESS': 840, 'ETN': 840, 'ETR': 840, 'EVRG': 840, 'EW': 840, 'EXC': 840, 'EXPD': 840, 'EXPE': 840, 'EXPN.L': 780, 'EXR': 840, 'F': 840, 'FAST': 840, 'FCX': 840, 'FDX': 840, 'FE': 840, 'FERG.L': 840, 'FFIV': 840, 'FISV': 840, 'FITB': 840, 'FLR': 840, 'FOX': 840, 'FOXA': 840, 'FRT': 840, 'FSLR': 840, 'GD': 840, 'GE': 840, 'GILD': 840, 'GIS': 840, 'GL': 840, 'GLEN.L': 720, 'GLW': 840, 'GM': 840, 'GOOG': 840, 'GOOGL': 840, 'GRMN': 840, 'GS': 840, 'GSK.L': 780, 'HAL': 840, 'HAS': 840, 'HBAN': 840, 'HCA': 840, 'HD': 840, 'HEI': 840, 'HES': 840, 'HIG': 840, 'HII': 840, 'HIK.L': 840, 'HLMA.L': 840, 'HLT': 840, 'HOLX': 840, 'HON': 840, 'HPE': 840, 'HPQ': 840, 'HR': 840, 'HRL': 840, 'HSBA.L': 840, 'HST': 840, 'HSY': 840, 'HWM': 840, 'IAG.L': 750, 'IBM': 840, 'ICE': 840, 'IDXX': 840, 'IEX': 840, 'IHG.L': 840, 'ILMN': 840, 'INTC': 840, 'INTU': 840, 'IP': 840, 'IQV': 840, 'IR': 840, 'IRM': 840, 'ISRG': 840, 'IT': 840, 'ITRK.L': 840, 'ITW': 840, 'IVZ': 840, 'J': 840, 'JBHT': 840, 'JCI': 840, 'JD.L': 840, 'JKHY': 840, 'JNJ': 840, 'JNPR': 840, 'JPM': 840, 'K': 840, 'KEY': 840, 'KGF.L': 840, 'KHC': 840, 'KLAC': 840, 'KMB': 840, 'KO': 840, 'KR': 840, 'L': 840, 'LAND.L': 780, 'LEN': 840, 'LGEN.L': 810, 'LH': 840, 'LHX': 840, 'LILAK': 840, 'LIN': 840, 'LKQ': 840, 'LLOY.L': 720, 'LMT': 840, 'LNC': 840, 'LNT': 840, 'LOW': 840, 'LPX': 840, 'LRCX': 840, 'LSEG.L': 840, 'LUMN': 840, 'LUV': 840, 'LVS': 840, 'LW': 840, 'LYB': 840, 'MA': 840, 'MAA': 840, 'MAS': 840, 'MCD': 840, 'MCHP': 840, 'MCO': 840, 'MDLZ': 840, 'MDT': 840, 'MET': 840, 'META': 840, 'MGM': 840, 'MHK': 840, 'MKC': 840, 'MKL': 840, 'MLM': 840, 'MMC': 840, 'MMM': 840, 'MNDI.L': 840, 'MNG.L': 660, 'MNST': 840, 'MO': 840, 'MPC': 840, 'MRK': 840, 'MRNA': 840, 'MRO': 840, 'MRO.L': 840, 'MS': 840, 'MSCI': 840, 'MSFT': 840, 'MSI': 840, 'MTB': 840, 'MTCH': 840, 'MU': 840, 'NDAQ': 840, 'NDSN': 840, 'NEE': 840, 'NEM': 840, 'NFLX': 840, 'NG.L': 840, 'NI': 840, 'NKE': 840, 'NOC': 840, 'NOW': 840, 'NSC': 840, 'NTRS': 840, 'NU': 840, 'NUE': 840, 'NVDA': 840, 'NVR': 840, 'NWL': 840, 'NXT.L': 840, 'NYT': 840, 'O': 840, 'OCDO.L': 840, 'OMC': 840, 'ON': 840, 'ORCL': 840, 'ORLY': 840, 'OTIS': 840, 'OXY': 840, 'PANW': 840, 'PARA': 840, 'PAYX': 840, 'PCAR': 840, 'PCG': 840, 'PEG': 840, 'PEP': 840, 'PFE': 840, 'PFG': 840, 'PG': 840, 'PGR': 840, 'PH': 840, 'PHM': 840, 'PHNX.L': 840, 'PKG': 840, 'PNC': 840, 'PNR': 840, 'PNW': 840, 'POOL': 840, 'PPG': 840, 'PPL': 840, 'PRU.L': 840, 'PSA': 840, 'PSN.L': 840, 'PWR': 840, 'PYPL': 840, 'QCOM': 840, 'QRVO': 840, 'RCL': 840, 'REG': 840, 'REGN': 840, 'REL.L': 840, 'RF': 840, 'RH': 840, 'RIO.L': 840, 'RJF': 840, 'RKT.L': 840, 'RMD': 840, 'ROK': 840, 'ROKU': 840, 'ROL': 840, 'ROP': 840, 'ROST': 840, 'RR.L': 840, 'RSG': 840, 'RTO.L': 840, 'RTX': 840, 'SBRY.L': 840, 'SBUX': 840, 'SCHW': 840, 'SCT.L': 840, 'SDR.L': 840, 'SEDG': 840, 'SEE': 840, 'SGE.L': 840, 'SGRO.L': 840, 'SHEL.L': 840, 'SHW': 840, 'SIRI': 840, 'SLB': 840, 'SMIN.L': 840, 'SMT.L': 840, 'SN.L': 840, 'SNA': 840, 'SNOW': 840, 'SNPS': 840, 'SO': 840, 'SPG': 840, 'SPGI': 840, 'SPX.L': 840, 'SRE': 840, 'SSE.L': 690, 'STAN.L': 840, 'STE': 840, 'STJ.L': 840, 'STNE': 840, 'STT': 840, 'STZ': 840, 'SWK': 840, 'SWKS': 840, 'SYF': 840, 'SYK': 840, 'SYY': 840, 'TAP': 840, 'TDG': 840, 'TDY': 840, 'TECH': 840, 'TEL': 840, 'TFC': 840, 'TFX': 840, 'TGT': 840, 'TJX': 840, 'TMO': 840, 'TMUS': 840, 'TRMB': 840, 'TROW': 840, 'TRV': 840, 'TSCO': 840, 'TSCO.L': 840, 'TSLA': 840, 'TSN': 840, 'TT': 840, 'TTD': 840, 'TTWO': 840, 'TW.L': 840, 'TXN': 840, 'TXT': 840, 'UAL': 840, 'UDR': 840, 'UHAL': 840, 'UHS': 840, 'ULVR.L': 840, 'UNH': 840, 'UNM': 840, 'UNP': 840, 'UPS': 840, 'URI': 840, 'USB': 840, 'UU.L': 810, 'V': 840, 'VFC': 840, 'VLO': 840, 'VMC': 840, 'VNO': 840, 'VOD.L': 840, 'VRSK': 840, 'VRSN': 840, 'VRTX': 840, 'VTR': 840, 'VZ': 840, 'WAB': 840, 'WAT': 840, 'WBA': 840, 'WDC': 840, 'WEC': 840, 'WFC': 840, 'WH': 840, 'WHR': 840, 'WM': 840, 'WMB': 840, 'WMT': 840, 'WPP.L': 840, 'WRB': 840, 'WST': 840, 'WTB.L': 540, 'WTW': 840, 'XEL': 840, 'XOM': 840, 'XRAY': 840, 'XYL': 840, 'YUM': 840, 'ZTS': 840, 'III.L': 840, 'HLN.L': 840, 'FRES.L': 750, 'MKS.L': 840, 'RMV.L': 840, 'ICG.L': 840, 'FCIT.L': 840, 'EZJ.L': 840, 'ENT.L': 840, 'EDV.L': 840, 'BEZ.L': 840, 'SVT.L': 750, 'BHP.L': 840, 'ABNB': 840, 'ADP': 840, 'APP': 840, 'ARM': 840, 'ASML': 840, 'AXON': 840, 'AZN': 840, 'CCEP': 840, 'CDNS': 840, 'CDW': 840, 'CEG': 840, 'CRWD': 840, 'CSGP': 840, 'CTSH': 840, 'DASH': 840, 'DDOG': 840, 'DXCM': 840, 'FANG': 840, 'FTNT': 840, 'GEHC': 840, 'GFS': 840, 'KDP': 840, 'LULU': 840, 'MAR': 840, 'MDB': 840, 'MELI': 840, 'MRVL': 840, 'NXPI': 840, 'ODFL': 840, 'PDD': 840, 'PLTR': 840, 'TEAM': 840, 'WBD': 840, 'WDAY': 840, 'ADYEN.AS': 840, 'AIL.DE': 840, 'AIR.PA': 840, 'AKZA.AS': 840, 'ALO.PA': 840, 'ABI.BR': 840, 'MT.AS': 840, 'ASML.AS': 840, 'CS.PA': 840, 'BNP.PA': 840, 'CAP.PA': 840, 'CA.PA': 840, 'SGO.PA': 840, 'ACA.PA': 840, 'BN.PA': 840, 'DSY.PA': 840, 'EDP.LS': 840, 'ENGI.PA': 840, 'EL.PA': 840, 'HEIA.AS': 840, 'KER.PA': 840, 'AD.AS': 840, 'DSM': 840, 'PHIA.AS': 840, 'OR.PA': 840, 'LR.PA': 840, 'MC.PA': 840, 'ML.PA': 840, 'ORA.PA': 840, 'RI.PA': 840, 'RNO.PA': 840, 'SAN.PA': 840, 'SU.PA': 840, 'GLE.PA': 840, 'SW.PA': 840, 'STMPA.PA': 840, 'TEP.PA': 840, 'TTE.PA': 840, 'URW.PA': 840, 'VIE.PA': 840, 'DG.PA': 840, 'VIV.PA': 840, 'WKL.AS': 840, 'RMS.PA': 840, 'ALV': 840, 'BUD': 840, 'BHP': 840, 'BP': 840, 'BTI': 840, 'GSK': 840, 'HSBC': 840, 'NSRGY': 840, 'NVS': 840, 'PM': 840, 'RHHBY': 840, 'RY': 840, 'SHEL': 840, 'SSNLF': 840, 'SNY': 840, 'SIEGY': 840, 'TSM': 840, 'TTE': 840, 'TM': 840}

micro_turbo_list = {'PSH.L': 9, 'IMI.L': 9, 'CTEC.L': 9, 'ABDN': 9, 'UTG.L': 9, 'SMDS.L': 9, 'LMP.L': 9, 'INF.L': 9, 'IMB.L': 9, 'HWDN.L': 9, 'Hiscox Ltd': 9, 'HL.L': 9, 'GAW.L': 9, 'DPLM.L': 9, 'DCC.L': 9, 'BTRW.L': 9, 'AHT.L': 9, 'ALW.L': 9, 'AAF.L': 9, 'NWG.L': 9, 'ABF.L': 9, 'IBE.MC': 9, '3IN.L': 9, 'A': 9, 'AAL': 9, 'AAL.L': 9, 'AAPL': 9, 'ABBV': 9, 'ABT': 9, 'ACI': 9, 'ACN': 9, 'ADBE': 9, 'ADI': 9, 'ADM': 9, 'ADM.L': 9, 'ADSK': 9, 'AEE': 9, 'AEP': 9, 'AES': 9, 'AFL': 9, 'AIG': 9, 'AKAM': 9, 'ALGN': 9, 'ALK': 9, 'ALL': 9, 'ALLE': 9, 'AMAT': 9, 'AMCR': 9, 'AMD': 9, 'AME': 9, 'AMGN': 9, 'AMZN': 9, 'ANET': 9, 'ANSS': 9, 'ANTO.L': 9, 'AON': 9, 'AOS': 9, 'APA': 9, 'APD': 9, 'APTV': 9, 'ARE': 9, 'ARW': 9, 'ATO': 9, 'AUTO.L': 9, 'AV.L': 9, 'AVB': 9, 'AVGO': 9, 'AXP': 9, 'AZN.L': 9, 'AZO': 9, 'BA': 9, 'BA.L': 9, 'BAC': 9, 'BALL': 9, 'BARC.L': 9, 'BATS.L': 9, 'BAX': 9, 'BBWI': 9, 'BBY': 9, 'BDEV.L': 9, 'BDX': 9, 'BEN': 9, 'BIIB': 9, 'BIO': 9, 'BKG.L': 9, 'BKNG': 9, 'BKR': 9, 'BLK': 9, 'BLND.L': 9, 'BMY': 9, 'BNZL.L': 9, 'BP.L': 9, 'BR': 9, 'BRBY.L': 9, 'BRK-B': 9, 'BSX': 9, 'BT-A.L': 9, 'BWA': 9, 'BXP': 9, 'BYDDY': 9, 'C': 9, 'CAG': 9, 'CAT': 9, 'CB': 9, 'CBOE': 9, 'CBRE': 9, 'CCH.L': 9, 'CE': 9, 'CHD': 9, 'CHTR': 9, 'CI': 9, 'CINF': 9, 'CL': 9, 'CLX': 9, 'CMCSA': 9, 'CME': 9, 'CMG': 9, 'CMI': 9, 'CMS': 9, 'CNA.L': 9, 'CNC': 9, 'CNP': 9, 'COO': 9, 'COP': 9, 'COST': 9, 'CPG.L': 9, 'CPRT': 9, 'CRDA.L': 9, 'CRH.L': 9, 'CRM': 9, 'CSCO': 9, 'CSX': 9, 'CTAS': 9, 'CTRA': 9, 'CVS': 9, 'CVX': 9, 'D': 9, 'DAL': 9, 'DD': 9, 'DE': 9, 'DEO': 9, 'DFS': 9, 'DG': 9, 'DGE.L': 9, 'DHI': 9, 'DHR': 9, 'DIS': 9, 'DLR': 9, 'DLTR': 9, 'DOV': 9, 'DOW': 9, 'DRI': 9, 'DTE': 9, 'DUK': 9, 'DVA': 9, 'DVN': 9, 'EA': 9, 'EBAY': 9, 'ECL': 9, 'ED': 9, 'EFX': 9, 'EIX': 9, 'EL': 9, 'ELV': 9, 'EMN': 9, 'EMR': 9, 'ENPH': 9, 'EOG': 9, 'EPAM': 9, 'EQIX': 9, 'EQR': 9, 'EQT': 9, 'ESS': 9, 'ETN': 9, 'ETR': 9, 'EVRG': 9, 'EW': 9, 'EXC': 9, 'EXPD': 9, 'EXPE': 9, 'EXPN.L': 9, 'EXR': 9, 'F': 9, 'FAST': 9, 'FCX': 9, 'FDX': 9, 'FE': 9, 'FERG.L': 9, 'FFIV': 9, 'FISV': 9, 'FITB': 9, 'FLR': 9, 'FOX': 9, 'FOXA': 9, 'FRT': 9, 'FSLR': 9, 'GD': 9, 'GE': 9, 'GILD': 9, 'GIS': 9, 'GL': 9, 'GLEN.L': 10, 'GLW': 9, 'GM': 9, 'GOOG': 9, 'GOOGL': 9, 'GRMN': 9, 'GS': 9, 'GSK.L': 9, 'HAL': 9, 'HAS': 9, 'HBAN': 9, 'HCA': 9, 'HD': 9, 'HEI': 9, 'HES': 9, 'HIG': 9, 'HII': 9, 'HIK.L': 9, 'HLMA.L': 9, 'HLT': 9, 'HOLX': 9, 'HON': 9, 'HPE': 9, 'HPQ': 9, 'HR': 9, 'HRL': 9, 'HSBA.L': 9, 'HST': 9, 'HSY': 9, 'HWM': 9, 'IAG.L': 9, 'IBM': 9, 'ICE': 9, 'IDXX': 9, 'IEX': 9, 'IHG.L': 9, 'ILMN': 9, 'INTC': 9, 'INTU': 9, 'IP': 9, 'IQV': 9, 'IR': 9, 'IRM': 9, 'ISRG': 9, 'IT': 9, 'ITRK.L': 9, 'ITW': 9, 'IVZ': 9, 'J': 9, 'JBHT': 9, 'JCI': 9, 'JD.L': 9, 'JKHY': 9, 'JNJ': 9, 'JNPR': 9, 'JPM': 9, 'K': 9, 'KEY': 9, 'KGF.L': 9, 'KHC': 9, 'KLAC': 9, 'KMB': 9, 'KO': 9, 'KR': 9, 'L': 9, 'LAND.L': 9, 'LEN': 9, 'LGEN.L': 9, 'LH': 9, 'LHX': 9, 'LILAK': 9, 'LIN': 9, 'LKQ': 9, 'LLOY.L': 9, 'LMT': 9, 'LNC': 9, 'LNT': 9, 'LOW': 9, 'LPX': 9, 'LRCX': 9, 'LSEG.L': 9, 'LUMN': 9, 'LUV': 9, 'LVS': 9, 'LW': 9, 'LYB': 9, 'MA': 9, 'MAA': 9, 'MAS': 9, 'MCD': 9, 'MCHP': 9, 'MCO': 9, 'MDLZ': 9, 'MDT': 9, 'MET': 9, 'META': 9, 'MGM': 9, 'MHK': 9, 'MKC': 9, 'MKL': 9, 'MLM': 9, 'MMC': 9, 'MMM': 9, 'MNDI.L': 9, 'MNG.L': 9, 'MNST': 9, 'MO': 9, 'MPC': 9, 'MRK': 9, 'MRNA': 9, 'MRO': 9, 'MRO.L': 9, 'MS': 9, 'MSCI': 9, 'MSFT': 9, 'MSI': 9, 'MTB': 9, 'MTCH': 9, 'MU': 9, 'NDAQ': 9, 'NDSN': 9, 'NEE': 9, 'NEM': 9, 'NFLX': 9, 'NG.L': 9, 'NI': 9, 'NKE': 9, 'NOC': 9, 'NOW': 9, 'NSC': 9, 'NTRS': 9, 'NU': 9, 'NUE': 9, 'NVDA': 9, 'NVR': 9, 'NWL': 9, 'NXT.L': 9, 'NYT': 9, 'O': 9, 'OCDO.L': 9, 'OMC': 9, 'ON': 9, 'ORCL': 9, 'ORLY': 9, 'OTIS': 9, 'OXY': 9, 'PANW': 9, 'PARA': 9, 'PAYX': 9, 'PCAR': 9, 'PCG': 9, 'PEG': 9, 'PEP': 9, 'PFE': 9, 'PFG': 9, 'PG': 9, 'PGR': 9, 'PH': 9, 'PHM': 9, 'PHNX.L': 9, 'PKG': 9, 'PNC': 9, 'PNR': 9, 'PNW': 9, 'POOL': 9, 'PPG': 9, 'PPL': 9, 'PRU.L': 9, 'PSA': 9, 'PSN.L': 9, 'PWR': 9, 'PYPL': 9, 'QCOM': 9, 'QRVO': 9, 'RCL': 9, 'REG': 9, 'REGN': 9, 'REL.L': 9, 'RF': 9, 'RH': 9, 'RIO.L': 9, 'RJF': 9, 'RKT.L': 9, 'RMD': 9, 'ROK': 9, 'ROKU': 9, 'ROL': 9, 'ROP': 9, 'ROST': 9, 'RR.L': 9, 'RSG': 9, 'RTO.L': 9, 'RTX': 9, 'SBRY.L': 9, 'SBUX': 9, 'SCHW': 9, 'SCT.L': 9, 'SDR.L': 9, 'SEDG': 9, 'SEE': 9, 'SGE.L': 9, 'SGRO.L': 9, 'SHEL.L': 9, 'SHW': 9, 'SIRI': 9, 'SLB': 9, 'SMIN.L': 9, 'SMT.L': 9, 'SN.L': 9, 'SNA': 9, 'SNOW': 9, 'SNPS': 9, 'SO': 9, 'SPG': 9, 'SPGI': 9, 'SPX.L': 9, 'SRE': 9, 'SSE.L': 9, 'STAN.L': 9, 'STE': 9, 'STJ.L': 9, 'STNE': 9, 'STT': 9, 'STZ': 9, 'SWK': 9, 'SWKS': 9, 'SYF': 9, 'SYK': 9, 'SYY': 9, 'TAP': 9, 'TDG': 9, 'TDY': 9, 'TECH': 9, 'TEL': 9, 'TFC': 9, 'TFX': 9, 'TGT': 9, 'TJX': 9, 'TMO': 9, 'TMUS': 9, 'TRMB': 9, 'TROW': 9, 'TRV': 9, 'TSCO': 9, 'TSCO.L': 9, 'TSLA': 9, 'TSN': 9, 'TT': 9, 'TTD': 9, 'TTWO': 9, 'TW.L': 9, 'TXN': 9, 'TXT': 9, 'UAL': 9, 'UDR': 9, 'UHAL': 9, 'UHS': 9, 'ULVR.L': 9, 'UNH': 9, 'UNM': 9, 'UNP': 9, 'UPS': 9, 'URI': 9, 'USB': 9, 'UU.L': 9, 'V': 9, 'VFC': 9, 'VLO': 9, 'VMC': 9, 'VNO': 9, 'VOD.L': 9, 'VRSK': 9, 'VRSN': 9, 'VRTX': 9, 'VTR': 9, 'VZ': 9, 'WAB': 9, 'WAT': 9, 'WBA': 9, 'WDC': 9, 'WEC': 9, 'WFC': 9, 'WH': 9, 'WHR': 9, 'WM': 9, 'WMB': 9, 'WMT': 9, 'WPP.L': 9, 'WRB': 9, 'WST': 9, 'WTB.L': 9, 'WTW': 9, 'XEL': 9, 'XOM': 9, 'XRAY': 9, 'XYL': 9, 'YUM': 9, 'ZTS': 9, 'III.L': 9, 'HLN.L': 9, 'FRES.L': 9, 'MKS.L': 9, 'RMV.L': 9, 'ICG.L': 9, 'FCIT.L': 9, 'EZJ.L': 9, 'ENT.L': 9, 'EDV.L': 9, 'BEZ.L': 9, 'SVT.L': 9, 'BHP.L': 9, 'ABNB': 9, 'ADP': 9, 'APP': 9, 'ARM': 9, 'ASML': 9, 'AXON': 9, 'AZN': 9, 'CCEP': 9, 'CDNS': 9, 'CDW': 9, 'CEG': 9, 'CRWD': 9, 'CSGP': 9, 'CTSH': 9, 'DASH': 9, 'DDOG': 9, 'DXCM': 9, 'FANG': 9, 'FTNT': 9, 'GEHC': 9, 'GFS': 9, 'KDP': 9, 'LULU': 9, 'MAR': 9, 'MDB': 9, 'MELI': 9, 'MRVL': 9, 'NXPI': 9, 'ODFL': 9, 'PDD': 9, 'PLTR': 9, 'TEAM': 9, 'WBD': 9, 'WDAY': 9, 'ADYEN.AS': 9, 'AIL.DE': 9, 'AIR.PA': 9, 'AKZA.AS': 9, 'ALO.PA': 9, 'ABI.BR': 9, 'MT.AS': 9, 'ASML.AS': 9, 'CS.PA': 9, 'BNP.PA': 9, 'CAP.PA': 9, 'CA.PA': 9, 'SGO.PA': 9, 'ACA.PA': 9, 'BN.PA': 9, 'DSY.PA': 9, 'EDP.LS': 9, 'ENGI.PA': 9, 'EL.PA': 9, 'HEIA.AS': 9, 'KER.PA': 9, 'AD.AS': 9, 'DSM': 9, 'PHIA.AS': 9, 'OR.PA': 9, 'LR.PA': 9, 'MC.PA': 9, 'ML.PA': 9, 'ORA.PA': 9, 'RI.PA': 9, 'RNO.PA': 9, 'SAN.PA': 9, 'SU.PA': 9, 'GLE.PA': 9, 'SW.PA': 9, 'STMPA.PA': 9, 'TEP.PA': 9, 'TTE.PA': 9, 'URW.PA': 9, 'VIE.PA': 9, 'DG.PA': 9, 'VIV.PA': 9, 'WKL.AS': 9, 'RMS.PA': 9, 'ALV': 9, 'BUD': 9, 'BHP': 9, 'BP': 9, 'BTI': 9, 'GSK': 9, 'HSBC': 9, 'NSRGY': 9, 'NVS': 9, 'PM': 9, 'RHHBY': 9, 'RY': 9, 'SHEL': 9, 'SSNLF': 9, 'SNY': 9, 'SIEGY': 9, 'TSM': 9, 'TTE': 9, 'TM': 9}
micro_fine_tune_list = {'PSH.L': 1, 'IMI.L': 1, 'CTEC.L': 1, 'ABDN': 1, 'UTG.L': 1, 'SMDS.L': 1, 'LMP.L': 1, 'INF.L': 1, 'IMB.L': 1, 'HWDN.L': 1, 'Hiscox Ltd': 1, 'HL.L': 1, 'GAW.L': 1, 'DPLM.L': 1, 'DCC.L': 1, 'BTRW.L': 1, 'AHT.L': 1, 'ALW.L': 1, 'AAF.L': 1, 'NWG.L': 1, 'ABF.L': 1, 'IBE.MC': 1, '3IN.L': 1, 'A': 1, 'AAL': 1, 'AAL.L': 1, 'AAPL': 1, 'ABBV': 1, 'ABT': 1, 'ACI': 1, 'ACN': 1, 'ADBE': 1, 'ADI': 1, 'ADM': 1, 'ADM.L': 1, 'ADSK': 1, 'AEE': 1, 'AEP': 1, 'AES': 1, 'AFL': 1, 'AIG': 1, 'AKAM': 1, 'ALGN': 1, 'ALK': 1, 'ALL': 1, 'ALLE': 1, 'AMAT': 1, 'AMCR': 1, 'AMD': 1, 'AME': 1, 'AMGN': 1, 'AMZN': 1, 'ANET': 1, 'ANSS': 1, 'ANTO.L': 1, 'AON': 1, 'AOS': 1, 'APA': 1, 'APD': 1, 'APTV': 1, 'ARE': 1, 'ARW': 1, 'ATO': 1, 'AUTO.L': 1, 'AV.L': 1, 'AVB': 1, 'AVGO': 1, 'AXP': 1, 'AZN.L': 1, 'AZO': 1, 'BA': 1, 'BA.L': 1, 'BAC': 1, 'BALL': 1, 'BARC.L': 1, 'BATS.L': 1, 'BAX': 1, 'BBWI': 1, 'BBY': 1, 'BDEV.L': 1, 'BDX': 1, 'BEN': 1, 'BIIB': 1, 'BIO': 1, 'BKG.L': 1, 'BKNG': 1, 'BKR': 1, 'BLK': 1, 'BLND.L': 1, 'BMY': 1, 'BNZL.L': 1, 'BP.L': 1, 'BR': 1, 'BRBY.L': 1, 'BRK-B': 1, 'BSX': 1, 'BT-A.L': 1, 'BWA': 1, 'BXP': 1, 'BYDDY': 1, 'C': 1, 'CAG': 1, 'CAT': 1, 'CB': 1, 'CBOE': 1, 'CBRE': 1, 'CCH.L': 1, 'CE': 1, 'CHD': 1, 'CHTR': 1, 'CI': 1, 'CINF': 1, 'CL': 1, 'CLX': 1, 'CMCSA': 1, 'CME': 1, 'CMG': 1, 'CMI': 1, 'CMS': 1, 'CNA.L': 1, 'CNC': 1, 'CNP': 1, 'COO': 1, 'COP': 1, 'COST': 1, 'CPG.L': 1, 'CPRT': 1, 'CRDA.L': 1, 'CRH.L': 1, 'CRM': 1, 'CSCO': 1, 'CSX': 1, 'CTAS': 1, 'CTRA': 1, 'CVS': 1, 'CVX': 1, 'D': 1, 'DAL': 1, 'DD': 1, 'DE': 1, 'DEO': 1, 'DFS': 1, 'DG': 1, 'DGE.L': 1, 'DHI': 1, 'DHR': 1, 'DIS': 1, 'DLR': 1, 'DLTR': 1, 'DOV': 1, 'DOW': 1, 'DRI': 1, 'DTE': 1, 'DUK': 1, 'DVA': 1, 'DVN': 1, 'EA': 1, 'EBAY': 1, 'ECL': 1, 'ED': 1, 'EFX': 1, 'EIX': 1, 'EL': 1, 'ELV': 1, 'EMN': 1, 'EMR': 1, 'ENPH': 1, 'EOG': 1, 'EPAM': 1, 'EQIX': 1, 'EQR': 1, 'EQT': 1, 'ESS': 1, 'ETN': 1, 'ETR': 1, 'EVRG': 1, 'EW': 1, 'EXC': 1, 'EXPD': 1, 'EXPE': 1, 'EXPN.L': 1, 'EXR': 1, 'F': 1, 'FAST': 1, 'FCX': 1, 'FDX': 1, 'FE': 1, 'FERG.L': 1, 'FFIV': 1, 'FISV': 1, 'FITB': 1, 'FLR': 1, 'FOX': 1, 'FOXA': 1, 'FRT': 1, 'FSLR': 1, 'GD': 1, 'GE': 1, 'GILD': 1, 'GIS': 1, 'GL': 1, 'GLEN.L': 3, 'GLW': 1, 'GM': 1, 'GOOG': 1, 'GOOGL': 1, 'GRMN': 1, 'GS': 1, 'GSK.L': 1, 'HAL': 1, 'HAS': 1, 'HBAN': 1, 'HCA': 1, 'HD': 1, 'HEI': 1, 'HES': 1, 'HIG': 1, 'HII': 1, 'HIK.L': 1, 'HLMA.L': 1, 'HLT': 1, 'HOLX': 1, 'HON': 1, 'HPE': 1, 'HPQ': 1, 'HR': 1, 'HRL': 1, 'HSBA.L': 1, 'HST': 1, 'HSY': 1, 'HWM': 1, 'IAG.L': 1, 'IBM': 1, 'ICE': 1, 'IDXX': 1, 'IEX': 1, 'IHG.L': 1, 'ILMN': 1, 'INTC': 1, 'INTU': 1, 'IP': 1, 'IQV': 1, 'IR': 1, 'IRM': 1, 'ISRG': 1, 'IT': 1, 'ITRK.L': 1, 'ITW': 1, 'IVZ': 1, 'J': 1, 'JBHT': 1, 'JCI': 1, 'JD.L': 1, 'JKHY': 1, 'JNJ': 1, 'JNPR': 1, 'JPM': 1, 'K': 1, 'KEY': 1, 'KGF.L': 1, 'KHC': 1, 'KLAC': 1, 'KMB': 1, 'KO': 1, 'KR': 1, 'L': 1, 'LAND.L': 1, 'LEN': 1, 'LGEN.L': 1, 'LH': 1, 'LHX': 1, 'LILAK': 1, 'LIN': 1, 'LKQ': 1, 'LLOY.L': 1, 'LMT': 1, 'LNC': 1, 'LNT': 1, 'LOW': 1, 'LPX': 1, 'LRCX': 1, 'LSEG.L': 1, 'LUMN': 1, 'LUV': 1, 'LVS': 1, 'LW': 1, 'LYB': 1, 'MA': 1, 'MAA': 1, 'MAS': 1, 'MCD': 1, 'MCHP': 1, 'MCO': 1, 'MDLZ': 1, 'MDT': 1, 'MET': 1, 'META': 1, 'MGM': 1, 'MHK': 1, 'MKC': 1, 'MKL': 1, 'MLM': 1, 'MMC': 1, 'MMM': 1, 'MNDI.L': 1, 'MNG.L': 1, 'MNST': 1, 'MO': 1, 'MPC': 1, 'MRK': 1, 'MRNA': 1, 'MRO': 1, 'MRO.L': 1, 'MS': 1, 'MSCI': 1, 'MSFT': 1, 'MSI': 1, 'MTB': 1, 'MTCH': 1, 'MU': 1, 'NDAQ': 1, 'NDSN': 1, 'NEE': 1, 'NEM': 1, 'NFLX': 1, 'NG.L': 1, 'NI': 1, 'NKE': 1, 'NOC': 1, 'NOW': 1, 'NSC': 1, 'NTRS': 1, 'NU': 1, 'NUE': 1, 'NVDA': 1, 'NVR': 1, 'NWL': 1, 'NXT.L': 1, 'NYT': 1, 'O': 1, 'OCDO.L': 1, 'OMC': 1, 'ON': 1, 'ORCL': 1, 'ORLY': 1, 'OTIS': 1, 'OXY': 1, 'PANW': 1, 'PARA': 1, 'PAYX': 1, 'PCAR': 1, 'PCG': 1, 'PEG': 1, 'PEP': 1, 'PFE': 1, 'PFG': 1, 'PG': 1, 'PGR': 1, 'PH': 1, 'PHM': 1, 'PHNX.L': 1, 'PKG': 1, 'PNC': 1, 'PNR': 1, 'PNW': 1, 'POOL': 1, 'PPG': 1, 'PPL': 1, 'PRU.L': 1, 'PSA': 1, 'PSN.L': 1, 'PWR': 1, 'PYPL': 1, 'QCOM': 1, 'QRVO': 1, 'RCL': 1, 'REG': 1, 'REGN': 1, 'REL.L': 1, 'RF': 1, 'RH': 1, 'RIO.L': 1, 'RJF': 1, 'RKT.L': 1, 'RMD': 1, 'ROK': 1, 'ROKU': 1, 'ROL': 1, 'ROP': 1, 'ROST': 1, 'RR.L': 1, 'RSG': 1, 'RTO.L': 1, 'RTX': 1, 'SBRY.L': 1, 'SBUX': 1, 'SCHW': 1, 'SCT.L': 1, 'SDR.L': 1, 'SEDG': 1, 'SEE': 1, 'SGE.L': 1, 'SGRO.L': 1, 'SHEL.L': 1, 'SHW': 1, 'SIRI': 1, 'SLB': 1, 'SMIN.L': 1, 'SMT.L': 1, 'SN.L': 1, 'SNA': 1, 'SNOW': 1, 'SNPS': 1, 'SO': 1, 'SPG': 1, 'SPGI': 1, 'SPX.L': 1, 'SRE': 1, 'SSE.L': 6, 'STAN.L': 1, 'STE': 1, 'STJ.L': 1, 'STNE': 1, 'STT': 1, 'STZ': 1, 'SWK': 1, 'SWKS': 1, 'SYF': 1, 'SYK': 1, 'SYY': 1, 'TAP': 1, 'TDG': 1, 'TDY': 1, 'TECH': 1, 'TEL': 1, 'TFC': 1, 'TFX': 1, 'TGT': 1, 'TJX': 1, 'TMO': 1, 'TMUS': 1, 'TRMB': 1, 'TROW': 1, 'TRV': 1, 'TSCO': 1, 'TSCO.L': 1, 'TSLA': 1, 'TSN': 1, 'TT': 1, 'TTD': 1, 'TTWO': 1, 'TW.L': 1, 'TXN': 1, 'TXT': 1, 'UAL': 1, 'UDR': 1, 'UHAL': 1, 'UHS': 1, 'ULVR.L': 1, 'UNH': 1, 'UNM': 1, 'UNP': 1, 'UPS': 1, 'URI': 1, 'USB': 1, 'UU.L': 1, 'V': 1, 'VFC': 1, 'VLO': 1, 'VMC': 1, 'VNO': 1, 'VOD.L': 1, 'VRSK': 1, 'VRSN': 1, 'VRTX': 1, 'VTR': 1, 'VZ': 1, 'WAB': 1, 'WAT': 1, 'WBA': 1, 'WDC': 1, 'WEC': 1, 'WFC': 1, 'WH': 1, 'WHR': 1, 'WM': 1, 'WMB': 1, 'WMT': 1, 'WPP.L': 1, 'WRB': 1, 'WST': 1, 'WTB.L': 1, 'WTW': 1, 'XEL': 1, 'XOM': 1, 'XRAY': 1, 'XYL': 1, 'YUM': 1, 'ZTS': 1, 'III.L': 1, 'HLN.L': 1, 'FRES.L': 1, 'MKS.L': 1, 'RMV.L': 1, 'ICG.L': 1, 'FCIT.L': 1, 'EZJ.L': 1, 'ENT.L': 1, 'EDV.L': 1, 'BEZ.L': 1, 'SVT.L': 1, 'BHP.L': 6, 'ABNB': 1, 'ADP': 1, 'APP': 1, 'ARM': 1, 'ASML': 1, 'AXON': 1, 'AZN': 1, 'CCEP': 1, 'CDNS': 1, 'CDW': 1, 'CEG': 1, 'CRWD': 1, 'CSGP': 1, 'CTSH': 1, 'DASH': 1, 'DDOG': 1, 'DXCM': 1, 'FANG': 1, 'FTNT': 1, 'GEHC': 1, 'GFS': 1, 'KDP': 1, 'LULU': 1, 'MAR': 1, 'MDB': 1, 'MELI': 1, 'MRVL': 1, 'NXPI': 1, 'ODFL': 1, 'PDD': 1, 'PLTR': 1, 'TEAM': 1, 'WBD': 1, 'WDAY': 1, 'ADYEN.AS': 1, 'AIL.DE': 1, 'AIR.PA': 1, 'AKZA.AS': 1, 'ALO.PA': 1, 'ABI.BR': 1, 'MT.AS': 1, 'ASML.AS': 1, 'CS.PA': 1, 'BNP.PA': 1, 'CAP.PA': 1, 'CA.PA': 1, 'SGO.PA': 1, 'ACA.PA': 1, 'BN.PA': 1, 'DSY.PA': 1, 'EDP.LS': 1, 'ENGI.PA': 1, 'EL.PA': 1, 'HEIA.AS': 1, 'KER.PA': 1, 'AD.AS': 1, 'DSM': 1, 'PHIA.AS': 1, 'OR.PA': 1, 'LR.PA': 1, 'MC.PA': 1, 'ML.PA': 1, 'ORA.PA': 1, 'RI.PA': 1, 'RNO.PA': 1, 'SAN.PA': 1, 'SU.PA': 1, 'GLE.PA': 1, 'SW.PA': 1, 'STMPA.PA': 1, 'TEP.PA': 1, 'TTE.PA': 1, 'URW.PA': 1, 'VIE.PA': 1, 'DG.PA': 1, 'VIV.PA': 1, 'WKL.AS': 1, 'RMS.PA': 1, 'ALV': 1, 'BUD': 1, 'BHP': 1, 'BP': 1, 'BTI': 1, 'GSK': 1, 'HSBC': 1, 'NSRGY': 1, 'NVS': 1, 'PM': 1, 'RHHBY': 1, 'RY': 1, 'SHEL': 1, 'SSNLF': 1, 'SNY': 1, 'SIEGY': 1, 'TSM': 1, 'TTE': 1, 'TM': 1}



companies_by_index = {
    "Adaptive Trading": {
        "BHP Group Ltd": "BHP.L",
        "SSE": "SSE.L",
        "Legal & General": "LGEN.L",
        "Rio Tinto": "RIO.L",
        "Glencore": "GLEN.L",
        "Visa Inc.": "V",
        "Mastercard Inc.": "MA",
        "Coca-Cola": "KO",
        "GlaxoSmithKline": "GSK.L",
        "BlackRock": "BLK",
        "BP": "BP.L",
        "National Grid": "NG.L",
        "United Utilities": "UU.L",
        "Shell": "SHEL.L",
        "M&G": "MNG.L",
        "Société Générale SA": "GLE.PA",
        "Johnson & Johnson": "JNJ",
        "Texas Instruments Incorporated": "TXN",
        "Thermo Fisher Scientific Inc.": "TMO",
        "Honeywell International Inc.": "HON",
        "CSX Corporation": "CSX",
        "Microchip Technology Incorporated": "MCHP",
        "GLOBALFOUNDRIES Inc.": "GFS",
        "Tesla, Inc.": "TSLA",
    },
    "FTSE 100": {
        "B&M European Value Retail SA": "BME.L",
        "Abrdn PLC": "ABDN.L",
        "UNITE Group plc": "UTG.L",
        "DS Smith plc": "SMDS.L",
        "Londonmetric Property PLC": "LMP.L",
        "Informa Plc": "INF.L",
        "Imperial Brands Group": "IMB.L",
        "Howden Joinery Group Plc": "HWDN.L",
        "Games Workshop Group PLC": "GAW.L",
        "3i Infrastructure": "3IN.L",
        "Ashtead Group": "AHT.L",
        "Alliance Witan": "ALW.L",
        "Airtel Africa": "AAF.L",
        "Admiral Group": "ADM.L",
        "Anglo American": "AAL.L",
        "Antofagasta": "ANTO.L",
        "Auto Trader Group": "AUTO.L",
        "Aviva": "AV.L",
        "AstraZeneca": "AZN.L",
        "BAE Systems": "BA.L",
        "Barclays": "BARC.L",
        "Barratt Redrow PLC": "BTRW.L",
        "British American Tobacco": "BATS.L",
        "BP Plc": "BP.L",
        "Berkeley Group Holdings": "BKG.L",
        "British Land": "BLND.L",
        "BT Group": "BT-A.L",
        "Bunzl": "BNZL.L",
        "Burberry": "BRBY.L",
        "Centrica": "CNA.L",
        "Coca-Cola HBC": "CCH.L",
        "Compass Group": "CPG.L",
        "CRH": "CRH.L",
        "Croda International": "CRDA.L",
        "Diageo": "DGE.L",
        "DCC plc": "DCC.L",
        "Diploma Plc": "DPLM.L",
        "Experian": "EXPN.L",
        "Glencore": "GLEN.L",
        "GlaxoSmithKline": "GSK.L",
        "Halma": "HLMA.L",
        "Hargreaves Lansdown PLC": "HL.L",
        "Hiscox Ltd": "HSX.L",
        "ConvaTec Group PLC": "CTEC.L",
        "HSBC Holdings": "HSBA.L",
        "Imperial Brands": "IMB.L",
        "InterContinental Hotels Group": "IHG.L",
        "International Consolidated Airlines Group": "IAG.L",
        "Intertek Group": "ITRK.L",
        "J Sainsbury": "SBRY.L",
        # "JD Sports Fashion": "JD.L",
        "Kingfisher": "KGF.L",
        "Land Securities Group": "LAND.L",
        "Legal & General": "LGEN.L",
        "Lloyds Banking Group": "LLOY.L",
        "London Stock Exchange Group": "LSEG.L",
        "M&G": "MNG.L",
        "Melrose Industries": "MRO.L",
        "Mondi": "MNDI.L",
        "National Grid": "NG.L",
        "Next": "NXT.L",
        # "Ocado Group": "OCDO.L",
        "Persimmon": "PSN.L",
        "Phoenix Group Holdings": "PHNX.L",
        "Prudential": "PRU.L",
        "Reckitt Benckiser": "RKT.L",
        "Relx": "REL.L",
        "Rentokil Initial": "RTO.L",
        "Rio Tinto": "RIO.L",
        "Rolls-Royce Holdings": "RR.L",
        "Sage Group": "SGE.L",
        "Schroders": "SDR.L",
        "Scottish Mortgage Investment Trust": "SMT.L",
        "Segro": "SGRO.L",
        "Smith & Nephew": "SN.L",
        "Smiths Group": "SMIN.L",
        "Spirax-Sarco Engineering": "SPX.L",
        "SSE": "SSE.L",
        "St. James's Place": "STJ.L",
        "Standard Chartered": "STAN.L",
        "Taylor Wimpey": "TW.L",
        "Tesco": "TSCO.L",
        "Unilever": "ULVR.L",
        "United Utilities": "UU.L",
        "Whitbread": "WTB.L",
        "WPP": "WPP.L",
        "Ferguson": "FERG.L",
        "Hikma Pharmaceuticals": "HIK.L",
        "InterContinental Hotels Group": "IHG.L",
        "Melrose Industries": "MRO.L",
        "Softcat": "SCT.L",
        "Taylor Wimpey": "TW.L",
        "Shell": "SHEL.L",
        "Haleon PLC": "HLN.L",
        "Fresnillo Plc": "FRES.L",
        "Marks and Spencer Group Plc": "MKS.L",
        "Rightmove Plc": "RMV.L",
        "Intermediate Capital Group plc": "ICG.L",
        "F&C Investment Trust PLC": "FCIT.L",
        "easyJet plc": "EZJ.L",
        "Entain PLC": "ENT.L",
        "Endeavour Mining PLC": "EDV.L",
        "Beazley PLC": "BEZ.L",
        "Severn Trent Plc": "SVT.L",
        "BHP Group Ltd": "BHP.L",
        "Associated British Foods plc": "ABF.L",
        "Natwest Group PLC": "NWG.L",
        "3i Group plc": "III.L",
        "Vodafone Group": "VOD.L",
        "Burberry": "BRBY.L",
        "IMI plc": "IMI.L",
        "Pershing Square Holdings Ltd": "PSH.L",
    },
    "Dow Jones Global 50": {
        "3M Co.": "MMM",
        "AbbVie Inc.": "ABBV",
        "Allianz SE": "ALV",
        "Alphabet Inc.": "GOOGL",
        "Amazon.com Inc.": "AMZN",
        "Amgen Inc.": "AMGN",
        "Anheuser-Busch InBev SA/NV": "BUD",
        "Apple Inc.": "AAPL",
        "BHP Group Ltd.": "BHP",
        "The Boeing Company": "BA",
        "BP": "BP",
        "British American Tobacco plc": "BTI",
        "Chevron Corporation": "CVX",
        "Cisco Systems Inc.": "CSCO",
        "Citigroup Inc.": "C",
        "The Coca-Cola Company": "KO",
        "DuPont de Nemours Inc.": "DD",
        "Exxon Mobil Corporation": "XOM",
        "Meta Platforms Inc.": "META",
        "General Electric Company": "GE",
        "GlaxoSmithKline plc": "GSK",
        "HSBC Holdings plc": "HSBC",
        "Intel Corporation": "INTC",
        "International Business Machines Corporation": "IBM",
        "Johnson & Johnson": "JNJ",
        "JPMorgan Chase & Co.": "JPM",
        "Mastercard Incorporated": "MA",
        "McDonald's Corporation": "MCD",
        "Merck & Co. Inc.": "MRK",
        "Microsoft Corporation": "MSFT",
        "Nestlé S.A.": "NSRGY",
        "Novartis AG": "NVS",
        "NVIDIA Corporation": "NVDA",
        "Oracle Corporation": "ORCL",
        "PepsiCo Inc.": "PEP",
        "Pfizer Inc.": "PFE",
        "Philip Morris International Inc.": "PM",
        "The Procter & Gamble Company": "PG",
        "Roche Holding AG": "RHHBY",
        "Royal Bank of Canada": "RY",
        "Shell plc": "SHEL",
        "Samsung Electronics Co. Ltd.": "SSNLF",
        "Sanofi": "SNY",
        "Siemens AG": "SIEGY",
        "Taiwan Semiconductor Manufacturing Company Limited": "TSM",
        "TotalEnergies SE": "TTE",
        "Visa Inc.": "V",
        "Toyota Motor Corporation": "TM",
        "Walmart Inc.": "WMT",
        "The Walt Disney Company": "DIS"
    },
    "Euronext 100": {
        "Adyen NV": "ADYEN.AS",
        "Air Liquide SA": "AIL.DE",
        "Airbus SE": "AIR.PA",
        "Akzo Nobel NV": "AKZA.AS",
        "Alstom SA": "ALO.PA",
        "Anheuser-Busch InBev SA/NV": "ABI.BR",
        "ArcelorMittal SA": "MT.AS",
        "ASML Holding NV": "ASML.AS",
        "Axa SA": "CS.PA",
        "BNP Paribas SA": "BNP.PA",
        "Capgemini SE": "CAP.PA",
        "Carrefour SA": "CA.PA",
        "Compagnie de Saint-Gobain SA": "SGO.PA",
        "Crédit Agricole SA": "ACA.PA",
        "Danone SA": "BN.PA",
        "Dassault Systèmes SE": "DSY.PA",
        "EDP - Energias de Portugal SA": "EDP.LS",
        "Engie SA": "ENGI.PA",
        "EssilorLuxottica SA": "EL.PA",
        "Heineken NV": "HEIA.AS",
        "Kering SA": "KER.PA",
        "Koninklijke Ahold Delhaize NV": "AD.AS",
        "Koninklijke DSM NV": "DSM",
        "Koninklijke Philips NV": "PHIA.AS",
        "L'Oréal SA": "OR.PA",
        "Legrand SA": "LR.PA",
        "LVMH Moët Hennessy – Louis Vuitton SE": "MC.PA",
        "Michelin (CGDE)": "ML.PA",
        "Orange SA": "ORA.PA",
        "Pernod Ricard SA": "RI.PA",
        "Renault SA": "RNO.PA",
        "Sanofi SA": "SAN.PA",
        "Schneider Electric SE": "SU.PA",
        "Société Générale SA": "GLE.PA",
        "Sodexo SA": "SW.PA",
        "STMicroelectronics NV": "STMPA.PA",
        "Teleperformance SE": "TEP.PA",
        "TotalEnergies SE": "TTE.PA",
        "Unibail-Rodamco-Westfield SE": "URW.PA",
        "Veolia Environnement SA": "VIE.PA",
        "Vinci SA": "DG.PA",
        "Vivendi SE": "VIV.PA",
        "Wolters Kluwer NV": "WKL.AS",
        "Airbus SE": "AIR.PA",
        "Hermes International SCA": "RMS.PA",
        "Iberdrola SA": "IBE.MC"
    },
    "Nasdaq 100": {
        "Apple Inc.": "AAPL",
        "Airbnb, Inc.": "ABNB",
        "Adobe Inc.": "ADBE",
        "Analog Devices, Inc.": "ADI",
        "Automatic Data Processing, Inc.": "ADP",
        "Autodesk, Inc.": "ADSK",
        "American Electric Power Company, Inc.": "AEP",
        "Applied Materials, Inc.": "AMAT",
        "Advanced Micro Devices, Inc.": "AMD",
        "Amgen Inc.": "AMGN",
        "Amazon.com, Inc.": "AMZN",
        "ANSYS, Inc.": "ANSS",
        "AppLovin Corporation": "APP",
        "Arm Holdings plc": "ARM",
        "ASML Holding N.V.": "ASML",
        "Broadcom Inc.": "AVGO",
        "Axon Enterprise, Inc.": "AXON",
        "AstraZeneca PLC": "AZN",
        "Biogen Inc.": "BIIB",
        "Booking Holdings Inc.": "BKNG",
        "Baker Hughes Company": "BKR",
        "Coca-Cola Europacific Partners PLC": "CCEP",
        "Cadence Design Systems, Inc.": "CDNS",
        "CDW Corporation": "CDW",
        "Constellation Energy Corporation": "CEG",
        "Charter Communications, Inc.": "CHTR",
        "Comcast Corporation": "CMCSA",
        "Costco Wholesale Corporation": "COST",
        "Copart, Inc.": "CPRT",
        "CrowdStrike Holdings, Inc.": "CRWD",
        "Cisco Systems, Inc.": "CSCO",
        "CoStar Group, Inc.": "CSGP",
        "CSX Corporation": "CSX",
        "Cintas Corporation": "CTAS",
        "Cognizant Technology Solutions Corporation": "CTSH",
        "DoorDash, Inc.": "DASH",
        "Datadog, Inc.": "DDOG",
        "DexCom, Inc.": "DXCM",
        "Electronic Arts Inc.": "EA",
        "Exelon Corporation": "EXC",
        "Diamondback Energy, Inc.": "FANG",
        "Fastenal Company": "FAST",
        "Fortinet, Inc.": "FTNT",
        "GE HealthCare Technologies Inc.": "GEHC",
        "GLOBALFOUNDRIES Inc.": "GFS",
        "Gilead Sciences, Inc.": "GILD",
        "Alphabet Inc. Class C": "GOOG",
        "Alphabet Inc. Class A": "GOOGL",
        "Honeywell International Inc.": "HON",
        "IDEXX Laboratories, Inc.": "IDXX",
        "Intel Corporation": "INTC",
        "Intuit Inc.": "INTU",
        "Intuitive Surgical, Inc.": "ISRG",
        "Keurig Dr Pepper Inc.": "KDP",
        "The Kraft Heinz Company": "KHC",
        "KLA Corporation": "KLAC",
        "Linde plc": "LIN",
        "Lam Research Corporation": "LRCX",
        "Lululemon Athletica Inc.": "LULU",
        "Marriott International, Inc.": "MAR",
        "Microchip Technology Incorporated": "MCHP",
        "MongoDB, Inc.": "MDB",
        "Mondelez International, Inc.": "MDLZ",
        "MercadoLibre, Inc.": "MELI",
        "Meta Platforms, Inc.": "META",
        "Monster Beverage Corporation": "MNST",
        "Marvell Technology, Inc.": "MRVL",
        "Microsoft Corporation": "MSFT",
        "Micron Technology, Inc.": "MU",
        "Netflix, Inc.": "NFLX",
        "NVIDIA Corporation": "NVDA",
        "NXP Semiconductors N.V.": "NXPI",
        "Old Dominion Freight Line, Inc.": "ODFL",
        "ON Semiconductor Corporation": "ON",
        "O'Reilly Automotive, Inc.": "ORLY",
        "Palo Alto Networks, Inc.": "PANW",
        "Paychex, Inc.": "PAYX",
        "PACCAR Inc": "PCAR",
        "PDD Holdings Inc.": "PDD",
        "PepsiCo, Inc.": "PEP",
        "Palantir Technologies Inc.": "PLTR",
        "PayPal Holdings, Inc.": "PYPL",
        "QUALCOMM Incorporated": "QCOM",
        "Regeneron Pharmaceuticals, Inc.": "REGN",
        "Roper Technologies, Inc.": "ROP",
        "Ross Stores, Inc.": "ROST",
        "Starbucks Corporation": "SBUX",
        "Synopsys, Inc.": "SNPS",
        "Atlassian Corporation Plc": "TEAM",
        "T-Mobile US, Inc.": "TMUS",
        "Tesla, Inc.": "TSLA",
        "The Trade Desk, Inc.": "TTD",
        "Take-Two Interactive Software, Inc.": "TTWO",
        "Texas Instruments Incorporated": "TXN",
        "Verisk Analytics, Inc.": "VRSK",
        "Vertex Pharmaceuticals Incorporated": "VRTX",
        "Warner Bros. Discovery, Inc.": "WBD",
        "Workday, Inc.": "WDAY"
    },
    "NYSE 100": {
        "3M Co.": "MMM",
        "Abbott Laboratories": "ABT",
        "Accenture Plc": "ACN",
        "AIG": "AIG",
        "Altria Group Inc.": "MO",
        "American Express Co.": "AXP",
        "AT&T Inc.": "T",
        "Bank of America Corp.": "BAC",
        "Bank of New York Mellon Corp.": "BK",
        "Boeing Co.": "BA",
        "Caterpillar Inc.": "CAT",
        "Chevron Corp.": "CVX",
        "Citigroup Inc.": "C",
        "Coca-Cola Co.": "KO",
        "ConocoPhillips": "COP",
        "Dow Inc.": "DOW",
        "Exxon Mobil Corp.": "XOM",
        "Ford Motor Co.": "F",
        "General Electric Co.": "GE",
        "Goldman Sachs Group Inc.": "GS",
        "Home Depot Inc.": "HD",
        "IBM": "IBM",
        "Johnson & Johnson": "JNJ",
        "JPMorgan Chase & Co.": "JPM",
        "McDonald's Corp.": "MCD",
        "Merck & Co. Inc.": "MRK",
        "Microsoft Corp.": "MSFT",
        "Nike Inc.": "NKE",
        "Pfizer Inc.": "PFE",
        "Procter & Gamble Co.": "PG",
        "Verizon Communications Inc.": "VZ",
        "Visa Inc.": "V",
        "Walmart Inc.": "WMT",
        "Walt Disney Co.": "DIS",
        "American International Group Inc.": "AIG",
        "Baxter International Inc.": "BAX",
        "Bayer AG": "BAYRY",
        "Berkshire Hathaway Inc.": "BRK-B",
        "BlackRock Inc.": "BLK",
        "Bristol-Myers Squibb Co.": "BMY",
        "Caterpillar Inc.": "CAT",
        "Chubb Ltd.": "CB",
        "Cisco Systems Inc.": "CSCO",
        "Colgate-Palmolive Co.": "CL",
        "Comcast Corp.": "CMCSA",
        "ConocoPhillips": "COP",
        "Danaher Corp.": "DHR",
        "Duke Energy Corp.": "DUK",
        "Emerson Electric Co.": "EMR",
        "Exxon Mobil Corp.": "XOM",
        "General Dynamics Corp.": "GD",
        "Honeywell International Inc.": "HON",
        "Intel Corp.": "INTC",
        "International Business Machines Corp.": "IBM",
        "Johnson & Johnson": "JNJ",
        "Lockheed Martin Corp.": "LMT",
        "Lowe's Companies Inc.": "LOW",
        "McDonald's Corp.": "MCD",
        "Medtronic Plc": "MDT",
        "Morgan Stanley": "MS",
        "NextEra Energy Inc.": "NEE",
        "PepsiCo Inc.": "PEP",
        "Philip Morris International Inc.": "PM",
        "Procter & Gamble Co.": "PG",
        "Raytheon Technologies Corp.": "RTX",
        "Salesforce Inc.": "CRM",
        "Schlumberger NV": "SLB",
        "Southern Co.": "SO",
        "Texas Instruments Inc.": "TXN",
        "Thermo Fisher Scientific Inc.": "TMO",
        "Union Pacific Corp.": "UNP",
        "United Parcel Service Inc.": "UPS",
        "UnitedHealth Group Inc.": "UNH",
        "Wells Fargo & Co.": "WFC",
        "Zoetis Inc.": "ZTS"
    },

    # "S&P 500": {
    #     "3M": "MMM", "A.O. Smith": "AOS", "Abbott Laboratories": "ABT", "Accenture": "ACN",
    #     "Adobe Inc.": "ADBE", "Advanced Micro Devices": "AMD",
    #     "AES Corp.": "AES", "Aflac": "AFL", "Agilent Technologies": "A", "Air Products and Chemicals": "APD",
    #     "Akamai Technologies": "AKAM", "Alaska Air Group": "ALK", "Albertsons": "ACI",
    #     "Alexandria Real Estate": "ARE",
    #     "Align Technology": "ALGN", "Allegion": "ALLE", "Alliant Energy": "LNT", "Allstate": "ALL",
    #     "Alphabet (Class A)": "GOOGL", "Alphabet (Class C)": "GOOG", "Altria": "MO", "Amazon.com": "AMZN",
    #     "Amcor": "AMCR", "Ameren Corporation": "AEE", "American Airlines": "AAL",
    #     "American Electric Power": "AEP", "American Express": "AXP", "American International Group": "AIG",
    #     "Ametek": "AME", "Amgen": "AMGN", "Analog Devices": "ADI",
    #     "Ansys": "ANSS", "Aon": "AON", "APA Corporation": "APA", "Apple Inc.": "AAPL",
    #     "Applied Materials": "AMAT", "Aptiv": "APTV", "Archer-Daniels-Midland": "ADM",
    #     "Arista Networks": "ANET", "Arrow Electronics": "ARW", "Atmos Energy": "ATO",
    #     "Autodesk": "ADSK", "AutoZone": "AZO", "AvalonBay Communities": "AVB",
    #     "Baker Hughes": "BKR", "Ball Corporation": "BALL", "Bank of America": "BAC", "Bath & Body Works": "BBWI",
    #     "Baxter International": "BAX", "Becton, Dickinson & Co.": "BDX",
    #     "Best Buy": "BBY", "Bio-Rad": "BIO", "Bio-Techne": "TECH", "Biogen": "BIIB",
    #     "BlackRock": "BLK", "Boeing": "BA", "Booking Holdings": "BKNG", "BorgWarner": "BWA",
    #     "Boston Properties": "BXP", "Boston Scientific": "BSX", "Bristol-Myers Squibb": "BMY",
    #     "Broadcom": "AVGO", "Broadridge Financial Solutions": "BR",
    #     "Cboe Global Markets": "CBOE", "CBRE Group": "CBRE", "Centene Corporation": "CNC",
    #     "CenterPoint Energy": "CNP", "Charles Schwab": "SCHW",
    #     "Charter Communications": "CHTR", "Chevron": "CVX", "Chipotle Mexican Grill": "CMG",
    #     "Chubb Limited": "CB", "Church & Dwight": "CHD", "Cigna": "CI", "Cincinnati Financial": "CINF",
    #     "Cintas": "CTAS", "Cisco Systems": "CSCO", "Citigroup": "C", "Clorox": "CLX",
    #     "CME Group": "CME", "CMS Energy": "CMS", "Coca-Cola": "KO", "Colgate-Palmolive": "CL",
    #     "Comcast": "CMCSA", "Conagra Brands": "CAG", "ConocoPhillips": "COP", "Consolidated Edison": "ED",
    #     "Constellation Brands": "STZ", "CooperCompanies": "COO", "Copart": "CPRT", "Corning": "GLW",
    #     "Costco": "COST", "Coterra Energy": "CTRA", "CSX": "CSX", "Cummins": "CMI",
    #     "CVS Health": "CVS", "D.R. Horton": "DHI", "Danaher": "DHR", "Darden Restaurants": "DRI",
    #     "DaVita": "DVA", "Deere & Company": "DE", "Delta Air Lines": "DAL", "Dentsply Sirona": "XRAY",
    #     "Devon Energy": "DVN", "Digital Realty": "DLR", "Discover Financial": "DFS",
    #     "Disney": "DIS", "Dollar General": "DG", "Dollar Tree": "DLTR", "Dominion Energy": "D",
    #     "Dover Corporation": "DOV", "Dow Inc.": "DOW", "DTE Energy": "DTE", "Duke Energy": "DUK",
    #     "DuPont": "DD", "Eastman Chemical": "EMN", "Eaton Corporation": "ETN", "eBay": "EBAY",
    #     "Ecolab": "ECL", "Edison International": "EIX", "Edwards Lifesciences": "EW",
    #     "Electronic Arts": "EA", "Elevance Health": "ELV", "Emerson Electric": "EMR",
    #     "Enphase Energy": "ENPH", "Entergy": "ETR", "EOG Resources": "EOG", "EPAM Systems": "EPAM",
    #     "EQT Corporation": "EQT", "Equifax": "EFX", "Equinix": "EQIX", "Equity Residential": "EQR",
    #     "Essex Property Trust": "ESS", "Estee Lauder": "EL", "Evergy": "EVRG", "Exelon": "EXC",
    #     "Expedia": "EXPE", "Expeditors International": "EXPD", "Extra Space Storage": "EXR",
    #     "Exxon Mobil": "XOM", "F5 Networks": "FFIV", "Fastenal": "FAST", "Federal Realty": "FRT",
    #     "FedEx": "FDX", "Fifth Third Bancorp": "FITB", "First Solar": "FSLR",
    #     "FirstEnergy": "FE", "Fiserv": "FISV", "Fluor": "FLR",
    #     "Ford Motor": "F", "Fox Corporation (Class A)": "FOXA", "Fox Corporation (Class B)": "FOX",
    #     "Franklin Resources": "BEN", "Freeport-McMoRan": "FCX", "Garmin": "GRMN", "Gartner": "IT",
    #     "General Dynamics": "GD", "General Electric": "GE", "General Mills": "GIS", "General Motors": "GM",
    #     "Gilead Sciences": "GILD", "Globe Life": "GL", "Goldman Sachs": "GS",
    #     "Halliburton": "HAL", "Hartford Financial Services": "HIG", "Hasbro": "HAS",
    #     "HCA Healthcare": "HCA", "Healthcare Realty Trust": "HR",
    #     "Heico Corporation": "HEI", "Hershey": "HSY", "Hess Corporation": "HES",
    #     "Hewlett Packard Enterprise": "HPE",
    #     "Hilton Worldwide": "HLT", "Hologic": "HOLX", "Home Depot": "HD", "Honeywell": "HON",
    #     "Hormel Foods": "HRL", "Host Hotels & Resorts": "HST", "Howmet Aerospace": "HWM",
    #     "Huntington Bancshares": "HBAN", "Huntington Ingalls Industries": "HII", "IBM": "IBM",
    #     "IDEX Corporation": "IEX", "IDEXX Laboratories": "IDXX", "Illinois Tool Works": "ITW",
    #     "Illumina": "ILMN", "Ingersoll Rand": "IR", "Intel": "INTC", "Intercontinental Exchange": "ICE",
    #     "International Paper": "IP", "Intuit": "INTU", "Intuitive Surgical": "ISRG", "Invesco": "IVZ",
    #     "IQVIA": "IQV", "Iron Mountain": "IRM", "J.B. Hunt": "JBHT", "Jack Henry": "JKHY",
    #     "Jacobs Engineering": "J", "JPMorgan Chase": "JPM", "Johnson & Johnson": "JNJ",
    #     "Juniper Networks": "JNPR", "Kellogg": "K", "KeyCorp": "KEY", "Kimberly-Clark": "KMB",
    #     "KLA Corporation": "KLAC", "Kroger": "KR", "L3Harris Technologies": "LHX",
    #     "Laboratory Corporation": "LH", "Lam Research": "LRCX", "Lamb Weston": "LW",
    #     "Las Vegas Sands": "LVS", "Lennar": "LEN", "Lincoln National": "LNC", "Linde": "LIN",
    #     "LKQ Corporation": "LKQ", "Lockheed Martin": "LMT", "Loews Corporation": "L",
    #     "Lowe's": "LOW", "Lumen Technologies": "LUMN", "LyondellBasell": "LYB",
    #     "M&T Bank": "MTB", "Marathon Oil": "MRO", "Marathon Petroleum": "MPC",
    #     "Marsh & McLennan": "MMC", "Martin Marietta": "MLM", "Masco": "MAS",
    #     "Mastercard": "MA", "Match Group": "MTCH", "McCormick & Company": "MKC",
    #     "McDonald's": "MCD", "Medtronic": "MDT", "Merck & Co.": "MRK", "Meta Platforms": "META",
    #     "MetLife": "MET", "MGM Resorts": "MGM", "Microchip Technology": "MCHP",
    #     "Micron Technology": "MU", "Microsoft": "MSFT", "Mid-America Apartments": "MAA",
    #     "Moderna": "MRNA", "Mohawk Industries": "MHK", "Molson Coors": "TAP", "Mondelez": "MDLZ",
    #     "Monster Beverage": "MNST", "Moody's": "MCO", "Morgan Stanley": "MS",
    #     "Motorola Solutions": "MSI", "MSCI Inc.": "MSCI", "Nasdaq": "NDAQ", "Netflix": "NFLX",
    #     "New York Times": "NYT", "Newell Brands": "NWL", "Newmont": "NEM", "NextEra Energy": "NEE",
    #     "Nike": "NKE", "NiSource": "NI", "Nordson": "NDSN", "Norfolk Southern": "NSC",
    #     "Northern Trust": "NTRS", "Northrop Grumman": "NOC", "Nucor": "NUE", "NVIDIA": "NVDA",
    #     "NVR, Inc.": "NVR", "Occidental Petroleum": "OXY", "Omnicom": "OMC", "ON Semiconductor": "ON",
    #     "Oracle": "ORCL", "O'Reilly Automotive": "ORLY", "Otis Worldwide": "OTIS", "PACCAR": "PCAR",
    #     "Packaging Corporation of America": "PKG", "Palo Alto Networks": "PANW", "Paramount": "PARA",
    #     "Parker-Hannifin": "PH", "Paychex": "PAYX", "PayPal": "PYPL", "Pentair": "PNR",
    #     "PepsiCo": "PEP", "Pfizer": "PFE", "PG&E": "PCG",
    #     "Pinnacle West": "PNW", "PNC Financial Services": "PNC",
    #     "Pool Corporation": "POOL", "PPG Industries": "PPG", "PPL Corporation": "PPL",
    #     "Principal Financial": "PFG", "Procter & Gamble": "PG", "Progressive": "PGR",
    #     "Public Service Enterprise": "PEG", "Public Storage": "PSA", "PulteGroup": "PHM",
    #     "Qorvo": "QRVO", "Qualcomm": "QCOM", "Quanta Services": "PWR",
    #     "Raymond James Financial": "RJF", "Raytheon Technologies": "RTX", "Realty Income": "O",
    #     "Regency Centers": "REG", "Regeneron": "REGN", "Regions Financial": "RF",
    #     "Republic Services": "RSG", "ResMed": "RMD", "Rockwell Automation": "ROK",
    #     "Roku": "ROKU", "Rollins": "ROL", "Roper Technologies": "ROP", "Ross Stores": "ROST",
    #     "Royal Caribbean": "RCL", "S&P Global": "SPGI", "Salesforce": "CRM", "Schlumberger": "SLB",
    #     "Sealed Air": "SEE", "Sempra Energy": "SRE", "ServiceNow": "NOW", "Sherwin-Williams": "SHW",
    #     "Simon Property Group": "SPG", "Skyworks Solutions": "SWKS", "Snap-on": "SNA",
    #     "SolarEdge Technologies": "SEDG", "Southern Company": "SO", "Southwest Airlines": "LUV",
    #     "Stanley Black & Decker": "SWK", "Starbucks": "SBUX", "State Street": "STT", "Steris": "STE",
    #     "Stryker": "SYK", "Synchrony Financial": "SYF", "Synopsys": "SNPS", "Sysco": "SYY",
    #     "T. Rowe Price": "TROW", "T-Mobile": "TMUS", "Take-Two Interactive": "TTWO", "Target": "TGT",
    #     "TE Connectivity": "TEL", "Teledyne Technologies": "TDY", "Teleflex": "TFX",
    #     "Texas Instruments": "TXN", "Textron": "TXT", "The Trade Desk": "TTD", "Thermo Fisher Scientific": "TMO",
    #     "TJX Companies": "TJX", "Tractor Supply": "TSCO", "Trane Technologies": "TT",
    #     "TransDigm Group": "TDG", "Travelers": "TRV", "Trimble": "TRMB", "Truist Financial": "TFC",
    #     "Tyson Foods": "TSN", "UDR, Inc.": "UDR", "U-Haul Holding": "UHAL", "Union Pacific": "UNP",
    #     "United Airlines": "UAL", "United Parcel Service": "UPS", "United Rentals": "URI",
    #     "UnitedHealth Group": "UNH", "Universal Health Services": "UHS", "Unum Group": "UNM",
    #     "V.F. Corporation": "VFC", "Valero Energy": "VLO", "Ventas": "VTR", "Verisk Analytics": "VRSK",
    #     "Verizon": "VZ", "Vertex Pharmaceuticals": "VRTX", "Visa": "V", "Vornado Realty": "VNO",
    #     "Vulcan Materials": "VMC", "W. R. Berkley": "WRB", "Wabtec": "WAB", "Walgreens Boots Alliance": "WBA",
    #     "Walmart": "WMT", "Waste Management": "WM", "Waters Corporation": "WAT",
    #     "WEC Energy Group": "WEC", "Wells Fargo": "WFC", "West Pharmaceutical Services": "WST",
    #     "Western Digital": "WDC", "Whirlpool": "WHR", "Williams Companies": "WMB",
    #     "Willis Towers Watson": "WTW", "Wyndham Hotels": "WH", "Xcel Energy": "XEL",
    #     "Xylem": "XYL", "Yum! Brands": "YUM", "Zoetis": "ZTS"
    # },
    "Berkshire Hathaway Holdings": {
        "Apple Inc.": "AAPL",
        "American Express": "AXP",
        "Bank of America": "BAC",
        "Chevron": "CVX",
        "Coca-Cola": "KO",
        "Kraft Heinz": "KHC",
        "Occidental Petroleum": "OXY",
        "Moody's": "MCO",
        "HP Inc.": "HPQ",
        "DaVita Inc.": "DVA",
        "Paramount Global": "PARA",
        "Louisiana-Pacific": "LPX",
        "Visa Inc.": "V",
        "Mastercard Inc.": "MA",
        "Johnson & Johnson": "JNJ",
        "Amazon.com": "AMZN",
        "Procter & Gamble": "PG",
        "U.S. Bancorp": "USB",
        "General Motors": "GM",
        "Charter Communications": "CHTR",
        "Celanese Corporation": "CE",
        "VeriSign Inc.": "VRSN",
        "Aon PLC": "AON",
        "Snowflake Inc.": "SNOW",
        "T-Mobile US": "TMUS",
        "BYD Co.": "BYDDY",
        "RH (Restoration Hardware)": "RH",
        "Markel Corporation": "MKL",
        "Sirius XM Holdings": "SIRI",
        "StoneCo Ltd.": "STNE",
        "Nu Holdings Ltd.": "NU",
        "Mondelez International": "MDLZ",
        "Bristol-Myers Squibb": "BMY",
        "AbbVie Inc.": "ABBV",
        "Merck & Co.": "MRK",
        "Johnson Controls": "JCI",
        "Liberty Latin America": "LILAK",
        "Diageo PLC": "DEO",
        "Globe Life Inc.": "GL",
        "Charter Communications": "CHTR",
        "Synchrony Financial": "SYF",
        "Berkshire Hathaway Energy": "BRK-B",
    },
    # "Adaptive Trading": {
    #     "Legal & General": "LGEN.L",
    #     "Rio Tinto": "RIO.L",
    #     "Glencore": "GLEN.L",
    #     "Visa Inc.": "V",
    #     "Mastercard Inc.": "MA",
    #     "Coca-Cola": "KO",
    #     "GlaxoSmithKline": "GSK.L",
    #     "BlackRock": "BLK",
    #     "BP": "BP.L",
    #     "National Grid": "NG.L",
    #     "SSE": "SSE.L",
    #     "United Utilities": "UU.L",
    #     "Shell": "SHEL.L",
    #     "M&G": "MNG.L",
    #     "Société Générale SA": "GLE.PA",
    #     "Johnson & Johnson": "JNJ",
    #     "Texas Instruments Incorporated": "TXN",
    #     "BHP Group Ltd": "BHP.L",
    #     "Thermo Fisher Scientific Inc.": "TMO",
    #     "Honeywell International Inc.": "HON",
    #     "CSX Corporation": "CSX",
    #     "Microchip Technology Incorporated": "MCHP",
    #     "GLOBALFOUNDRIES Inc.": "GFS",
    #     "Tesla, Inc.": "TSLA",

    # }

}