import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

companies_by_index = {
    "Dow Jones Global 50": {
        "3M Co.": "MMM",
        "AbbVie Inc.": "ABBV",
        "Allianz SE": "ALV",
        "Alphabet Inc.": "GOOGL",
        "Amazon.com Inc.": "AMZN",
        "Amgen Inc.": "AMGN",
        "Anheuser-Busch InBev SA/NV": "BUD",
        "Apple Inc.": "AAPL",
        "BHP Group Ltd.": "BHP",
        "The Boeing Company": "BA",
        "BP": "BP",
        "British American Tobacco plc": "BTI",
        "Chevron Corporation": "CVX",
        "Cisco Systems Inc.": "CSCO",
        "Citigroup Inc.": "C",
        "The Coca-Cola Company": "KO",
        "DuPont de Nemours Inc.": "DD",
        "Exxon Mobil Corporation": "XOM",
        "Meta Platforms Inc.": "META",
        "General Electric Company": "GE",
        "GlaxoSmithKline plc": "GSK",
        "HSBC Holdings plc": "HSBC",
        "Intel Corporation": "INTC",
        "International Business Machines Corporation": "IBM",
        "Johnson & Johnson": "JNJ",
        "JPMorgan Chase & Co.": "JPM",
        "Mastercard Incorporated": "MA",
        "McDonald's Corporation": "MCD",
        "Merck & Co. Inc.": "MRK",
        "Microsoft Corporation": "MSFT",
        "Nestlé S.A.": "NSRGY",
        "Novartis AG": "NVS",
        "NVIDIA Corporation": "NVDA",
        "Oracle Corporation": "ORCL",
        "PepsiCo Inc.": "PEP",
        "Pfizer Inc.": "PFE",
        "Philip Morris International Inc.": "PM",
        "The Procter & Gamble Company": "PG",
        "Roche Holding AG": "RHHBY",
        "Royal Bank of Canada": "RY",
        "Shell plc": "SHEL",
        "Samsung Electronics Co. Ltd.": "SSNLF",
        "Sanofi": "SNY",
        "Siemens AG": "SIEGY",
        "Taiwan Semiconductor Manufacturing Company Limited": "TSM",
        "TotalEnergies SE": "TTE",
        "Visa Inc.": "V",
        "Toyota Motor Corporation": "TM",
        "Walmart Inc.": "WMT",
        "The Walt Disney Company": "DIS"
    },
    "Euronext 100": {
        "Adyen NV": "ADYEN.AS",
        "Air Liquide SA": "AIL.DE",
        "Airbus SE": "AIR.PA",
        "Akzo Nobel NV": "AKZA.AS",
        "Alstom SA": "ALO.PA",
        "Anheuser-Busch InBev SA/NV": "ABI.BR",
        "ArcelorMittal SA": "MT.AS",
        "ASML Holding NV": "ASML.AS",
        "Axa SA": "CS.PA",
        "BNP Paribas SA": "BNP.PA",
        "Capgemini SE": "CAP.PA",
        "Carrefour SA": "CA.PA",
        "Compagnie de Saint-Gobain SA": "SGO.PA",
        "Crédit Agricole SA": "ACA.PA",
        "Danone SA": "BN.PA",
        "Dassault Systèmes SE": "DSY.PA",
        "EDP - Energias de Portugal SA": "EDP.LS",
        "Engie SA": "ENGI.PA",
        "EssilorLuxottica SA": "EL.PA",
        "Heineken NV": "HEIA.AS",
        "Kering SA": "KER.PA",
        "Koninklijke Ahold Delhaize NV": "AD.AS",
        "Koninklijke DSM NV": "DSM",
        "Koninklijke Philips NV": "PHIA.AS",
        "L'Oréal SA": "OR.PA",
        "Legrand SA": "LR.PA",
        "LVMH Moët Hennessy – Louis Vuitton SE": "MC.PA",
        "Michelin (CGDE)": "ML.PA",
        "Orange SA": "ORA.PA",
        "Pernod Ricard SA": "RI.PA",
        "Renault SA": "RNO.PA",
        "Sanofi SA": "SAN.PA",
        "Schneider Electric SE": "SU.PA",
        "Société Générale SA": "GLE.PA",
        "Sodexo SA": "SW.PA",
        "STMicroelectronics NV": "STMPA.PA",
        "Teleperformance SE": "TEP.PA",
        "TotalEnergies SE": "TTE.PA",
        "Unibail-Rodamco-Westfield SE": "URW.PA",
        "Veolia Environnement SA": "VIE.PA",
        "Vinci SA": "DG.PA",
        "Vivendi SE": "VIV.PA",
        "Wolters Kluwer NV": "WKL.AS",
        "Airbus SE": "AIR.PA",
        "Hermes International SCA": "RMS.PA",
        "Iberdrola SA": "IBE.MC"
    },
    "Nasdaq 100": {
        "Apple Inc.": "AAPL",
        "Airbnb, Inc.": "ABNB",
        "Adobe Inc.": "ADBE",
        "Analog Devices, Inc.": "ADI",
        "Automatic Data Processing, Inc.": "ADP",
        "Autodesk, Inc.": "ADSK",
        "American Electric Power Company, Inc.": "AEP",
        "Applied Materials, Inc.": "AMAT",
        "Advanced Micro Devices, Inc.": "AMD",
        "Amgen Inc.": "AMGN",
        "Amazon.com, Inc.": "AMZN",
        "ANSYS, Inc.": "ANSS",
        "AppLovin Corporation": "APP",
        "Arm Holdings plc": "ARM",
        "ASML Holding N.V.": "ASML",
        "Broadcom Inc.": "AVGO",
        "Axon Enterprise, Inc.": "AXON",
        "AstraZeneca PLC": "AZN",
        "Biogen Inc.": "BIIB",
        "Booking Holdings Inc.": "BKNG",
        "Baker Hughes Company": "BKR",
        "Coca-Cola Europacific Partners PLC": "CCEP",
        "Cadence Design Systems, Inc.": "CDNS",
        "CDW Corporation": "CDW",
        "Constellation Energy Corporation": "CEG",
        "Charter Communications, Inc.": "CHTR",
        "Comcast Corporation": "CMCSA",
        "Costco Wholesale Corporation": "COST",
        "Copart, Inc.": "CPRT",
        "CrowdStrike Holdings, Inc.": "CRWD",
        "Cisco Systems, Inc.": "CSCO",
        "CoStar Group, Inc.": "CSGP",
        "CSX Corporation": "CSX",
        "Cintas Corporation": "CTAS",
        "Cognizant Technology Solutions Corporation": "CTSH",
        "DoorDash, Inc.": "DASH",
        "Datadog, Inc.": "DDOG",
        "DexCom, Inc.": "DXCM",
        "Electronic Arts Inc.": "EA",
        "Exelon Corporation": "EXC",
        "Diamondback Energy, Inc.": "FANG",
        "Fastenal Company": "FAST",
        "Fortinet, Inc.": "FTNT",
        "GE HealthCare Technologies Inc.": "GEHC",
        "GLOBALFOUNDRIES Inc.": "GFS",
        "Gilead Sciences, Inc.": "GILD",
        "Alphabet Inc. Class C": "GOOG",
        "Alphabet Inc. Class A": "GOOGL",
        "Honeywell International Inc.": "HON",
        "IDEXX Laboratories, Inc.": "IDXX",
        "Intel Corporation": "INTC",
        "Intuit Inc.": "INTU",
        "Intuitive Surgical, Inc.": "ISRG",
        "Keurig Dr Pepper Inc.": "KDP",
        "The Kraft Heinz Company": "KHC",
        "KLA Corporation": "KLAC",
        "Linde plc": "LIN",
        "Lam Research Corporation": "LRCX",
        "Lululemon Athletica Inc.": "LULU",
        "Marriott International, Inc.": "MAR",
        "Microchip Technology Incorporated": "MCHP",
        "MongoDB, Inc.": "MDB",
        "Mondelez International, Inc.": "MDLZ",
        "MercadoLibre, Inc.": "MELI",
        "Meta Platforms, Inc.": "META",
        "Monster Beverage Corporation": "MNST",
        "Marvell Technology, Inc.": "MRVL",
        "Microsoft Corporation": "MSFT",
        "Micron Technology, Inc.": "MU",
        "Netflix, Inc.": "NFLX",
        "NVIDIA Corporation": "NVDA",
        "NXP Semiconductors N.V.": "NXPI",
        "Old Dominion Freight Line, Inc.": "ODFL",
        "ON Semiconductor Corporation": "ON",
        "O'Reilly Automotive, Inc.": "ORLY",
        "Palo Alto Networks, Inc.": "PANW",
        "Paychex, Inc.": "PAYX",
        "PACCAR Inc": "PCAR",
        "PDD Holdings Inc.": "PDD",
        "PepsiCo, Inc.": "PEP",
        "Palantir Technologies Inc.": "PLTR",
        "PayPal Holdings, Inc.": "PYPL",
        "QUALCOMM Incorporated": "QCOM",
        "Regeneron Pharmaceuticals, Inc.": "REGN",
        "Roper Technologies, Inc.": "ROP",
        "Ross Stores, Inc.": "ROST",
        "Starbucks Corporation": "SBUX",
        "Synopsys, Inc.": "SNPS",
        "Atlassian Corporation Plc": "TEAM",
        "T-Mobile US, Inc.": "TMUS",
        "Tesla, Inc.": "TSLA",
        "The Trade Desk, Inc.": "TTD",
        "Take-Two Interactive Software, Inc.": "TTWO",
        "Texas Instruments Incorporated": "TXN",
        "Verisk Analytics, Inc.": "VRSK",
        "Vertex Pharmaceuticals Incorporated": "VRTX",
        "Warner Bros. Discovery, Inc.": "WBD",
        "Workday, Inc.": "WDAY"
    },
    "NYSE 100": {
        "3M Co.": "MMM",
        "Abbott Laboratories": "ABT",
        "Accenture Plc": "ACN",
        "AIG": "AIG",
        "Altria Group Inc.": "MO",
        "American Express Co.": "AXP",
        "AT&T Inc.": "T",
        "Bank of America Corp.": "BAC",
        "Bank of New York Mellon Corp.": "BK",
        "Boeing Co.": "BA",
        "Caterpillar Inc.": "CAT",
        "Chevron Corp.": "CVX",
        "Citigroup Inc.": "C",
        "Coca-Cola Co.": "KO",
        "ConocoPhillips": "COP",
        "Dow Inc.": "DOW",
        "Exxon Mobil Corp.": "XOM",
        "Ford Motor Co.": "F",
        "General Electric Co.": "GE",
        "Goldman Sachs Group Inc.": "GS",
        "Home Depot Inc.": "HD",
        "IBM": "IBM",
        "Johnson & Johnson": "JNJ",
        "JPMorgan Chase & Co.": "JPM",
        "McDonald's Corp.": "MCD",
        "Merck & Co. Inc.": "MRK",
        "Microsoft Corp.": "MSFT",
        "Nike Inc.": "NKE",
        "Pfizer Inc.": "PFE",
        "Procter & Gamble Co.": "PG",
        "Verizon Communications Inc.": "VZ",
        "Visa Inc.": "V",
        "Walmart Inc.": "WMT",
        "Walt Disney Co.": "DIS",
        "American International Group Inc.": "AIG",
        "Baxter International Inc.": "BAX",
        "Bayer AG": "BAYRY",
        "Berkshire Hathaway Inc.": "BRK-B",
        "BlackRock Inc.": "BLK",
        "Bristol-Myers Squibb Co.": "BMY",
        "Caterpillar Inc.": "CAT",
        "Chubb Ltd.": "CB",
        "Cisco Systems Inc.": "CSCO",
        "Colgate-Palmolive Co.": "CL",
        "Comcast Corp.": "CMCSA",
        "ConocoPhillips": "COP",
        "Danaher Corp.": "DHR",
        "Duke Energy Corp.": "DUK",
        "Emerson Electric Co.": "EMR",
        "Exxon Mobil Corp.": "XOM",
        "General Dynamics Corp.": "GD",
        "Honeywell International Inc.": "HON",
        "Intel Corp.": "INTC",
        "International Business Machines Corp.": "IBM",
        "Johnson & Johnson": "JNJ",
        "Lockheed Martin Corp.": "LMT",
        "Lowe's Companies Inc.": "LOW",
        "McDonald's Corp.": "MCD",
        "Medtronic Plc": "MDT",
        "Morgan Stanley": "MS",
        "NextEra Energy Inc.": "NEE",
        "PepsiCo Inc.": "PEP",
        "Philip Morris International Inc.": "PM",
        "Procter & Gamble Co.": "PG",
        "Raytheon Technologies Corp.": "RTX",
        "Salesforce Inc.": "CRM",
        "Schlumberger NV": "SLB",
        "Southern Co.": "SO",
        "Texas Instruments Inc.": "TXN",
        "Thermo Fisher Scientific Inc.": "TMO",
        "Union Pacific Corp.": "UNP",
        "United Parcel Service Inc.": "UPS",
        "UnitedHealth Group Inc.": "UNH",
        "Wells Fargo & Co.": "WFC",
        "Zoetis Inc.": "ZTS"
    },
    "FTSE 100": {
        "B&M European Value Retail SA": "BME.L",
        "Abrdn PLC": "ABDN.L",
        "UNITE Group plc": "UTG.L",
        "DS Smith plc": "SMDS.L",
        "Londonmetric Property PLC": "LMP.L",
        "Informa Plc": "INF.L",
        "Imperial Brands Group": "IMB.L",
        "Howden Joinery Group Plc": "HWDN.L",
        "Games Workshop Group PLC": "GAW.L",
        "3i Infrastructure": "3IN.L",
        "Ashtead Group": "AHT.L",
        "Alliance Witan": "ALW.L",
        "Airtel Africa": "AAF.L",
        "Admiral Group": "ADM.L",
        "Anglo American": "AAL.L",
        "Antofagasta": "ANTO.L",
        "Auto Trader Group": "AUTO.L",
        "Aviva": "AV.L",
        "AstraZeneca": "AZN.L",
        "BAE Systems": "BA.L",
        "Barclays": "BARC.L",
        "Barratt Redrow PLC": "BTRW.L",
        "British American Tobacco": "BATS.L",
        "BP Plc": "BP.L",
        "Berkeley Group Holdings": "BKG.L",
        "British Land": "BLND.L",
        "BT Group": "BT-A.L",
        "Bunzl": "BNZL.L",
        "Burberry": "BRBY.L",
        "Centrica": "CNA.L",
        "Coca-Cola HBC": "CCH.L",
        "Compass Group": "CPG.L",
        "CRH": "CRH.L",
        "Croda International": "CRDA.L",
        "Diageo": "DGE.L",
        "DCC plc": "DCC.L",
        "Diploma Plc": "DPLM.L",
        "Experian": "EXPN.L",
        "Glencore": "GLEN.L",
        "GlaxoSmithKline": "GSK.L",
        "Halma": "HLMA.L",
        "Hargreaves Lansdown PLC": "HL.L",
        "Hiscox Ltd": "HSX.L",
        "ConvaTec Group PLC": "CTEC.L",
        "HSBC Holdings": "HSBA.L",
        "Imperial Brands": "IMB.L",
        "InterContinental Hotels Group": "IHG.L",
        "International Consolidated Airlines Group": "IAG.L",
        "Intertek Group": "ITRK.L",
        "J Sainsbury": "SBRY.L",
        # "JD Sports Fashion": "JD.L",
        "Kingfisher": "KGF.L",
        "Land Securities Group": "LAND.L",
        "Legal & General": "LGEN.L",
        "Lloyds Banking Group": "LLOY.L",
        "London Stock Exchange Group": "LSEG.L",
        "M&G": "MNG.L",
        "Melrose Industries": "MRO.L",
        "Mondi": "MNDI.L",
        "National Grid": "NG.L",
        "Next": "NXT.L",
        # "Ocado Group": "OCDO.L",
        "Persimmon": "PSN.L",
        "Phoenix Group Holdings": "PHNX.L",
        "Prudential": "PRU.L",
        "Reckitt Benckiser": "RKT.L",
        "Relx": "REL.L",
        "Rentokil Initial": "RTO.L",
        "Rio Tinto": "RIO.L",
        "Rolls-Royce Holdings": "RR.L",
        "Sage Group": "SGE.L",
        "Schroders": "SDR.L",
        "Scottish Mortgage Investment Trust": "SMT.L",
        "Segro": "SGRO.L",
        "Smith & Nephew": "SN.L",
        "Smiths Group": "SMIN.L",
        "Spirax-Sarco Engineering": "SPX.L",
        "SSE": "SSE.L",
        "St. James's Place": "STJ.L",
        "Standard Chartered": "STAN.L",
        "Taylor Wimpey": "TW.L",
        "Tesco": "TSCO.L",
        "Unilever": "ULVR.L",
        "United Utilities": "UU.L",
        "Whitbread": "WTB.L",
        "WPP": "WPP.L",
        "Ferguson": "FERG.L",
        "Hikma Pharmaceuticals": "HIK.L",
        "InterContinental Hotels Group": "IHG.L",
        "Melrose Industries": "MRO.L",
        "Softcat": "SCT.L",
        "Taylor Wimpey": "TW.L",
        "Shell": "SHEL.L",
        "Haleon PLC": "HLN.L",
        "Fresnillo Plc": "FRES.L",
        "Marks and Spencer Group Plc": "MKS.L",
        "Rightmove Plc": "RMV.L",
        "Intermediate Capital Group plc": "ICG.L",
        "F&C Investment Trust PLC": "FCIT.L",
        "easyJet plc": "EZJ.L",
        "Entain PLC": "ENT.L",
        "Endeavour Mining PLC": "EDV.L",
        "Beazley PLC": "BEZ.L",
        "Severn Trent Plc": "SVT.L",
        "BHP Group Ltd": "BHP.L",
        "Associated British Foods plc": "ABF.L",
        "Natwest Group PLC": "NWG.L",
        "3i Group plc": "III.L",
        "Vodafone Group": "VOD.L",
        "Burberry": "BRBY.L",
        "IMI plc": "IMI.L",
        "Pershing Square Holdings Ltd": "PSH.L",

    },
    # "S&P 500": {
    #     "3M": "MMM", "A.O. Smith": "AOS", "Abbott Laboratories": "ABT", "Accenture": "ACN",
    #     "Adobe Inc.": "ADBE", "Advanced Micro Devices": "AMD",
    #     "AES Corp.": "AES", "Aflac": "AFL", "Agilent Technologies": "A", "Air Products and Chemicals": "APD",
    #     "Akamai Technologies": "AKAM", "Alaska Air Group": "ALK", "Albertsons": "ACI",
    #     "Alexandria Real Estate": "ARE",
    #     "Align Technology": "ALGN", "Allegion": "ALLE", "Alliant Energy": "LNT", "Allstate": "ALL",
    #     "Alphabet (Class A)": "GOOGL", "Alphabet (Class C)": "GOOG", "Altria": "MO", "Amazon.com": "AMZN",
    #     "Amcor": "AMCR", "Ameren Corporation": "AEE", "American Airlines": "AAL",
    #     "American Electric Power": "AEP", "American Express": "AXP", "American International Group": "AIG",
    #     "Ametek": "AME", "Amgen": "AMGN", "Analog Devices": "ADI",
    #     "Ansys": "ANSS", "Aon": "AON", "APA Corporation": "APA", "Apple Inc.": "AAPL",
    #     "Applied Materials": "AMAT", "Aptiv": "APTV", "Archer-Daniels-Midland": "ADM",
    #     "Arista Networks": "ANET", "Arrow Electronics": "ARW", "Atmos Energy": "ATO",
    #     "Autodesk": "ADSK", "AutoZone": "AZO", "AvalonBay Communities": "AVB",
    #     "Baker Hughes": "BKR", "Ball Corporation": "BALL", "Bank of America": "BAC", "Bath & Body Works": "BBWI",
    #     "Baxter International": "BAX", "Becton, Dickinson & Co.": "BDX",
    #     "Best Buy": "BBY", "Bio-Rad": "BIO", "Bio-Techne": "TECH", "Biogen": "BIIB",
    #     "BlackRock": "BLK", "Boeing": "BA", "Booking Holdings": "BKNG", "BorgWarner": "BWA",
    #     "Boston Properties": "BXP", "Boston Scientific": "BSX", "Bristol-Myers Squibb": "BMY",
    #     "Broadcom": "AVGO", "Broadridge Financial Solutions": "BR",
    #     "Cboe Global Markets": "CBOE", "CBRE Group": "CBRE", "Centene Corporation": "CNC",
    #     "CenterPoint Energy": "CNP", "Charles Schwab": "SCHW",
    #     "Charter Communications": "CHTR", "Chevron": "CVX", "Chipotle Mexican Grill": "CMG",
    #     "Chubb Limited": "CB", "Church & Dwight": "CHD", "Cigna": "CI", "Cincinnati Financial": "CINF",
    #     "Cintas": "CTAS", "Cisco Systems": "CSCO", "Citigroup": "C", "Clorox": "CLX",
    #     "CME Group": "CME", "CMS Energy": "CMS", "Coca-Cola": "KO", "Colgate-Palmolive": "CL",
    #     "Comcast": "CMCSA", "Conagra Brands": "CAG", "ConocoPhillips": "COP", "Consolidated Edison": "ED",
    #     "Constellation Brands": "STZ", "CooperCompanies": "COO", "Copart": "CPRT", "Corning": "GLW",
    #     "Costco": "COST", "Coterra Energy": "CTRA", "CSX": "CSX", "Cummins": "CMI",
    #     "CVS Health": "CVS", "D.R. Horton": "DHI", "Danaher": "DHR", "Darden Restaurants": "DRI",
    #     "DaVita": "DVA", "Deere & Company": "DE", "Delta Air Lines": "DAL", "Dentsply Sirona": "XRAY",
    #     "Devon Energy": "DVN", "Digital Realty": "DLR", "Discover Financial": "DFS",
    #     "Disney": "DIS", "Dollar General": "DG", "Dollar Tree": "DLTR", "Dominion Energy": "D",
    #     "Dover Corporation": "DOV", "Dow Inc.": "DOW", "DTE Energy": "DTE", "Duke Energy": "DUK",
    #     "DuPont": "DD", "Eastman Chemical": "EMN", "Eaton Corporation": "ETN", "eBay": "EBAY",
    #     "Ecolab": "ECL", "Edison International": "EIX", "Edwards Lifesciences": "EW",
    #     "Electronic Arts": "EA", "Elevance Health": "ELV", "Emerson Electric": "EMR",
    #     "Enphase Energy": "ENPH", "Entergy": "ETR", "EOG Resources": "EOG", "EPAM Systems": "EPAM",
    #     "EQT Corporation": "EQT", "Equifax": "EFX", "Equinix": "EQIX", "Equity Residential": "EQR",
    #     "Essex Property Trust": "ESS", "Estee Lauder": "EL", "Evergy": "EVRG", "Exelon": "EXC",
    #     "Expedia": "EXPE", "Expeditors International": "EXPD", "Extra Space Storage": "EXR",
    #     "Exxon Mobil": "XOM", "F5 Networks": "FFIV", "Fastenal": "FAST", "Federal Realty": "FRT",
    #     "FedEx": "FDX", "Fifth Third Bancorp": "FITB", "First Solar": "FSLR",
    #     "FirstEnergy": "FE", "Fiserv": "FISV", "Fluor": "FLR",
    #     "Ford Motor": "F", "Fox Corporation (Class A)": "FOXA", "Fox Corporation (Class B)": "FOX",
    #     "Franklin Resources": "BEN", "Freeport-McMoRan": "FCX", "Garmin": "GRMN", "Gartner": "IT",
    #     "General Dynamics": "GD", "General Electric": "GE", "General Mills": "GIS", "General Motors": "GM",
    #     "Gilead Sciences": "GILD", "Globe Life": "GL", "Goldman Sachs": "GS",
    #     "Halliburton": "HAL", "Hartford Financial Services": "HIG", "Hasbro": "HAS",
    #     "HCA Healthcare": "HCA", "Healthcare Realty Trust": "HR",
    #     "Heico Corporation": "HEI", "Hershey": "HSY", "Hess Corporation": "HES",
    #     "Hewlett Packard Enterprise": "HPE",
    #     "Hilton Worldwide": "HLT", "Hologic": "HOLX", "Home Depot": "HD", "Honeywell": "HON",
    #     "Hormel Foods": "HRL", "Host Hotels & Resorts": "HST", "Howmet Aerospace": "HWM",
    #     "Huntington Bancshares": "HBAN", "Huntington Ingalls Industries": "HII", "IBM": "IBM",
    #     "IDEX Corporation": "IEX", "IDEXX Laboratories": "IDXX", "Illinois Tool Works": "ITW",
    #     "Illumina": "ILMN", "Ingersoll Rand": "IR", "Intel": "INTC", "Intercontinental Exchange": "ICE",
    #     "International Paper": "IP", "Intuit": "INTU", "Intuitive Surgical": "ISRG", "Invesco": "IVZ",
    #     "IQVIA": "IQV", "Iron Mountain": "IRM", "J.B. Hunt": "JBHT", "Jack Henry": "JKHY",
    #     "Jacobs Engineering": "J", "JPMorgan Chase": "JPM", "Johnson & Johnson": "JNJ",
    #     "Juniper Networks": "JNPR", "Kellogg": "K", "KeyCorp": "KEY", "Kimberly-Clark": "KMB",
    #     "KLA Corporation": "KLAC", "Kroger": "KR", "L3Harris Technologies": "LHX",
    #     "Laboratory Corporation": "LH", "Lam Research": "LRCX", "Lamb Weston": "LW",
    #     "Las Vegas Sands": "LVS", "Lennar": "LEN", "Lincoln National": "LNC", "Linde": "LIN",
    #     "LKQ Corporation": "LKQ", "Lockheed Martin": "LMT", "Loews Corporation": "L",
    #     "Lowe's": "LOW", "Lumen Technologies": "LUMN", "LyondellBasell": "LYB",
    #     "M&T Bank": "MTB", "Marathon Oil": "MRO", "Marathon Petroleum": "MPC",
    #     "Marsh & McLennan": "MMC", "Martin Marietta": "MLM", "Masco": "MAS",
    #     "Mastercard": "MA", "Match Group": "MTCH", "McCormick & Company": "MKC",
    #     "McDonald's": "MCD", "Medtronic": "MDT", "Merck & Co.": "MRK", "Meta Platforms": "META",
    #     "MetLife": "MET", "MGM Resorts": "MGM", "Microchip Technology": "MCHP",
    #     "Micron Technology": "MU", "Microsoft": "MSFT", "Mid-America Apartments": "MAA",
    #     "Moderna": "MRNA", "Mohawk Industries": "MHK", "Molson Coors": "TAP", "Mondelez": "MDLZ",
    #     "Monster Beverage": "MNST", "Moody's": "MCO", "Morgan Stanley": "MS",
    #     "Motorola Solutions": "MSI", "MSCI Inc.": "MSCI", "Nasdaq": "NDAQ", "Netflix": "NFLX",
    #     "New York Times": "NYT", "Newell Brands": "NWL", "Newmont": "NEM", "NextEra Energy": "NEE",
    #     "Nike": "NKE", "NiSource": "NI", "Nordson": "NDSN", "Norfolk Southern": "NSC",
    #     "Northern Trust": "NTRS", "Northrop Grumman": "NOC", "Nucor": "NUE", "NVIDIA": "NVDA",
    #     "NVR, Inc.": "NVR", "Occidental Petroleum": "OXY", "Omnicom": "OMC", "ON Semiconductor": "ON",
    #     "Oracle": "ORCL", "O'Reilly Automotive": "ORLY", "Otis Worldwide": "OTIS", "PACCAR": "PCAR",
    #     "Packaging Corporation of America": "PKG", "Palo Alto Networks": "PANW", "Paramount": "PARA",
    #     "Parker-Hannifin": "PH", "Paychex": "PAYX", "PayPal": "PYPL", "Pentair": "PNR",
    #     "PepsiCo": "PEP", "Pfizer": "PFE", "PG&E": "PCG",
    #     "Pinnacle West": "PNW", "PNC Financial Services": "PNC",
    #     "Pool Corporation": "POOL", "PPG Industries": "PPG", "PPL Corporation": "PPL",
    #     "Principal Financial": "PFG", "Procter & Gamble": "PG", "Progressive": "PGR",
    #     "Public Service Enterprise": "PEG", "Public Storage": "PSA", "PulteGroup": "PHM",
    #     "Qorvo": "QRVO", "Qualcomm": "QCOM", "Quanta Services": "PWR",
    #     "Raymond James Financial": "RJF", "Raytheon Technologies": "RTX", "Realty Income": "O",
    #     "Regency Centers": "REG", "Regeneron": "REGN", "Regions Financial": "RF",
    #     "Republic Services": "RSG", "ResMed": "RMD", "Rockwell Automation": "ROK",
    #     "Roku": "ROKU", "Rollins": "ROL", "Roper Technologies": "ROP", "Ross Stores": "ROST",
    #     "Royal Caribbean": "RCL", "S&P Global": "SPGI", "Salesforce": "CRM", "Schlumberger": "SLB",
    #     "Sealed Air": "SEE", "Sempra Energy": "SRE", "ServiceNow": "NOW", "Sherwin-Williams": "SHW",
    #     "Simon Property Group": "SPG", "Skyworks Solutions": "SWKS", "Snap-on": "SNA",
    #     "SolarEdge Technologies": "SEDG", "Southern Company": "SO", "Southwest Airlines": "LUV",
    #     "Stanley Black & Decker": "SWK", "Starbucks": "SBUX", "State Street": "STT", "Steris": "STE",
    #     "Stryker": "SYK", "Synchrony Financial": "SYF", "Synopsys": "SNPS", "Sysco": "SYY",
    #     "T. Rowe Price": "TROW", "T-Mobile": "TMUS", "Take-Two Interactive": "TTWO", "Target": "TGT",
    #     "TE Connectivity": "TEL", "Teledyne Technologies": "TDY", "Teleflex": "TFX",
    #     "Texas Instruments": "TXN", "Textron": "TXT", "The Trade Desk": "TTD", "Thermo Fisher Scientific": "TMO",
    #     "TJX Companies": "TJX", "Tractor Supply": "TSCO", "Trane Technologies": "TT",
    #     "TransDigm Group": "TDG", "Travelers": "TRV", "Trimble": "TRMB", "Truist Financial": "TFC",
    #     "Tyson Foods": "TSN", "UDR, Inc.": "UDR", "U-Haul Holding": "UHAL", "Union Pacific": "UNP",
    #     "United Airlines": "UAL", "United Parcel Service": "UPS", "United Rentals": "URI",
    #     "UnitedHealth Group": "UNH", "Universal Health Services": "UHS", "Unum Group": "UNM",
    #     "V.F. Corporation": "VFC", "Valero Energy": "VLO", "Ventas": "VTR", "Verisk Analytics": "VRSK",
    #     "Verizon": "VZ", "Vertex Pharmaceuticals": "VRTX", "Visa": "V", "Vornado Realty": "VNO",
    #     "Vulcan Materials": "VMC", "W. R. Berkley": "WRB", "Wabtec": "WAB", "Walgreens Boots Alliance": "WBA",
    #     "Walmart": "WMT", "Waste Management": "WM", "Waters Corporation": "WAT",
    #     "WEC Energy Group": "WEC", "Wells Fargo": "WFC", "West Pharmaceutical Services": "WST",
    #     "Western Digital": "WDC", "Whirlpool": "WHR", "Williams Companies": "WMB",
    #     "Willis Towers Watson": "WTW", "Wyndham Hotels": "WH", "Xcel Energy": "XEL",
    #     "Xylem": "XYL", "Yum! Brands": "YUM", "Zoetis": "ZTS"
    # },
    "Berkshire Hathaway Holdings": {
        "Apple Inc.": "AAPL",
        "American Express": "AXP",
        "Bank of America": "BAC",
        "Chevron": "CVX",
        "Coca-Cola": "KO",
        "Kraft Heinz": "KHC",
        "Occidental Petroleum": "OXY",
        "Moody's": "MCO",
        "HP Inc.": "HPQ",
        "DaVita Inc.": "DVA",
        "Paramount Global": "PARA",
        "Louisiana-Pacific": "LPX",
        "Visa Inc.": "V",
        "Mastercard Inc.": "MA",
        "Johnson & Johnson": "JNJ",
        "Amazon.com": "AMZN",
        "Procter & Gamble": "PG",
        "U.S. Bancorp": "USB",
        "General Motors": "GM",
        "Charter Communications": "CHTR",
        "Celanese Corporation": "CE",
        "VeriSign Inc.": "VRSN",
        "Aon PLC": "AON",
        "Snowflake Inc.": "SNOW",
        "T-Mobile US": "TMUS",
        "BYD Co.": "BYDDY",
        "RH (Restoration Hardware)": "RH",
        "Markel Corporation": "MKL",
        "Sirius XM Holdings": "SIRI",
        "StoneCo Ltd.": "STNE",
        "Nu Holdings Ltd.": "NU",
        "Mondelez International": "MDLZ",
        "Bristol-Myers Squibb": "BMY",
        "AbbVie Inc.": "ABBV",
        "Merck & Co.": "MRK",
        "Johnson Controls": "JCI",
        "Liberty Latin America": "LILAK",
        "Diageo PLC": "DEO",
        "Globe Life Inc.": "GL",
        "Charter Communications": "CHTR",
        "Synchrony Financial": "SYF",
        "Berkshire Hathaway Energy": "BRK-B",
    },
    "Adaptive Trading": {
        "Legal & General": "LGEN.L",
        "Rio Tinto": "RIO.L",
        "Glencore": "GLEN.L",
        "Visa Inc.": "V",
        "Mastercard Inc.": "MA",
        "Coca-Cola": "KO",
        "GlaxoSmithKline": "GSK.L",
        "BlackRock": "BLK",
        "BP": "BP.L",
        "National Grid": "NG.L",
        "SSE": "SSE.L",
        "United Utilities": "UU.L",
        "Shell": "SHEL.L",
        "M&G": "MNG.L",
        "Société Générale SA": "GLE.PA",
        "Johnson & Johnson": "JNJ",
        "Texas Instruments Incorporated": "TXN",
        "BHP Group Ltd": "BHP.L",
        "Thermo Fisher Scientific Inc.": "TMO",
        "Honeywell International Inc.": "HON",
        "CSX Corporation": "CSX",
        "Microchip Technology Incorporated": "MCHP",
        "GLOBALFOUNDRIES Inc.": "GFS",
        "Tesla, Inc.": "TSLA",

    }
}

ftse_tickers = list(companies_by_index["FTSE 100"].values())

# FTSE 100 tickers
# tickers = ["sse.l"]

# Function to download historical data for a list of tickers
def download_historical_data(tickers):
    end_date = datetime.now()
    start_date = end_date - timedelta(days=5*365)
    
    data = pd.DataFrame()
    
    for ticker in tickers:
        stock_data = yf.download(ticker, start=start_date, end=end_date, auto_adjust=False)
        stock_data = stock_data[['Close']].round(2)  # Keep only 'Close' price and round to 2 decimal places
        stock_data.columns = [ticker]  # Rename the column to the ticker symbol
        data = pd.concat([data, stock_data], axis=1)
    
    return data

# List of FTSE tickers (example tickers, replace with actual FTSE tickers)
# ftse_tickers = ['sse.l']  # Replace with actual FTSE tickers

# Streamlit app
st.title("FTSE Historical Stock Data Downloader")

st.write("This app downloads the past 5 years of daily close prices for FTSE tickers and allows you to download the data as a CSV file.")

# Download historical data
if st.button("Download Historical Data"):
    with st.spinner("Downloading data..."):
        historical_data = download_historical_data(ftse_tickers)
        historical_data.to_csv("ftse_historical_data.csv")
        st.success("Data downloaded successfully!")

# Display the data
if st.checkbox("Show historical data"):
    try:
        historical_data = pd.read_csv("ftse_historical_data.csv", index_col=0)
        st.write(historical_data)
    except FileNotFoundError:
        st.error("No data available. Please download the data first.")

# Allow users to download the CSV file
if st.button("Download CSV"):
    try:
        with open("ftse_historical_data.csv", "rb") as file:
            btn = st.download_button(
                label="Download CSV",
                data=file,
                file_name="ftse_historical_data.csv",
                mime="text/csv",
            )
    except FileNotFoundError:
        st.error("No data available. Please download the data first.")